#!/bin/bash
#------------------------------------------------------------------------------
# @description Render the local stack's two env files from cnf, OUTSIDE the
# @description repo (they are per tree and per developer, never committed):
# @description   compose.env  compose interpolation: images, 127.0.0.1 host
# @description                ports, the Postgres container's credentials,
# @description                the hub image + env file for this tree, the
# @description                WUI image, port and source dir
# @description   hub.env      the hub's runtime env for ENV=lde, one KEY=value
# @description                per line: cnf env.hub.env, env.auth.social.env,
# @description                env.auth.native.env and env.mail.env (the names
# @description                published in all.env.yaml; a PLACEHOLDER value is
# @description                dropped), {lde_wui_port} / {lde_hub_port} filled
# @description                in, then the env.lde.switches applied (below).
# @description Both land in $LDE_STATE_DIR (see do_lde_cnf), mode 0600.
# @description
# @description Switches (cnf env.lde.switches, env overrides via do_lde_cnf):
# @description   LDE_AUTH_NATIVE=1     SPOOL_HUB_AUTH_NATIVE_ENABLED=true
# @description   LDE_AUTH_PROVIDERS=p  SPOOL_HUB_AUTH_PROVIDERS=p; each
# @description                         SPOOL_HUB_AUTH_<P>_CLIENT_ID/_SECRET and
# @description                         an optional SPOOL_HUB_AUTH_IDP_BASE_URL
# @description                         come from the caller's env (fail fast)
# @description   LDE_WUI_DISPATCH=1    SPOOL_HUB_WUI_DISPATCH=true with an
# @description                         ephemeral box-wui key (do_spl_pin_box_wui)
# @description An auth switch also sets SPOOL_HUB_AUTH_SESSION_KEY from
# @description $LDE_STATE_DIR/auth-session.key (generated once per tree, 0600,
# @description never logged), so sessions survive a hub restart.
# @example ./run -a do_gen_docker_env
# @example LDE_AUTH_NATIVE=1 LDE_WUI_DISPATCH=1 ./run -a do_gen_docker_env
#------------------------------------------------------------------------------
do_gen_docker_env() {
  do_lde_cnf || return 1
  local tmp
  tmp="$(mktemp "$LDE_STATE_DIR/.hub.env.XXXXXX")" || return 1
  # yq prints each entry as KEY=value; values are single-line strings. A
  # PLACEHOLDER is a cloud slot nobody filled: lde never boots on one.
  yq -r '[.env.hub.env, .env.auth.social.env // {}, .env.auth.native.env // {}, .env.mail.env // {}] | .[]
         | to_entries | .[] | select((.value | tostring | test("PLACEHOLDER")) | not)
         | .key + "=" + (.value | tostring)' "$LDE_CNF" >"$tmp" || { rm -f "$tmp"; return 1; }
  _gde_ports "$tmp" && _gde_switches "$tmp" || { rm -f "$tmp" "$tmp".*; return 1; }
  if grep -qvE '^SPOOL_HUB_[A-Z_]+=|^STORAGE_EMULATOR_HOST=' "$tmp"; then
    do_log "FATAL hub.env holds a name outside SPOOL_HUB_* / STORAGE_EMULATOR_HOST: $(grep -vE '^SPOOL_HUB_[A-Z_]+=|^STORAGE_EMULATOR_HOST=' "$tmp" | cut -d= -f1 | tr '\n' ' ')"
    rm -f "$tmp"; return 1
  fi
  # The WUI dev server is the one cross-origin caller the lde hub allows. The
  # allow-list follows the WUI ports actually in use on this box, so a WUI on
  # an overridden port never needs a CORS proxy:
  #   - this tree's LDE_WUI_PORT
  #   - every sibling tree's LDE_WUI_PORT (from its rendered compose.env next
  #     to ours), so a worktree WUI can read the main checkout's hub
  #   - LDE_WUI_EXTRA_ORIGINS, comma-separated http(s)://host:port (e.g. a
  #     host `nuxi dev --port 3067`)
  # A value change, never a new name; the hub re-reads it when do_wui_up (or
  # do_setup_app_inf) re-applies the hub service.
  _gde_cors "$tmp" || { rm -f "$tmp" "$tmp".*; return 1; }
  chmod 600 "$tmp" && mv -f "$tmp" "$LDE_HUB_ENV_FILE"

  umask 077
  cat >"$LDE_COMPOSE_ENV" <<ENV
# GENERATED by do_gen_docker_env from $LDE_CNF_DIR/lde.env.yaml. Do not edit.
LDE_PG_IMAGE=$LDE_PG_IMAGE
LDE_PG_PORT=$LDE_PG_PORT
LDE_PG_DB=$LDE_PG_DB
LDE_PG_USER=$LDE_PG_USER
LDE_PG_PASSWORD=$LDE_PG_PASSWORD
LDE_GCS_IMAGE=$LDE_GCS_IMAGE
LDE_GCS_PORT=$LDE_GCS_PORT
LDE_HUB_IMAGE=$LDE_HUB_IMAGE
LDE_HUB_PORT=$LDE_HUB_PORT
LDE_HUB_CONTAINER_PORT=$LDE_HUB_CONTAINER_PORT
LDE_HUB_ENV_FILE=$LDE_HUB_ENV_FILE
LDE_SMOKE_TENANT=$LDE_SMOKE_TENANT
LDE_WUI_IMAGE=$LDE_WUI_IMAGE
LDE_WUI_PORT=$LDE_WUI_PORT
LDE_WUI_SRC=$LDE_WUI_SRC
LDE_WUI_UID=$LDE_WUI_UID
LDE_WUI_GID=$LDE_WUI_GID
ENV
  do_log "INFO rendered $LDE_COMPOSE_ENV and $LDE_HUB_ENV_FILE ($(wc -l <"$LDE_HUB_ENV_FILE") hub vars) for tree $LDE_TREE_SLUG"
  do_log "INFO lde switches: auth_native=$LDE_AUTH_NATIVE auth_providers=${LDE_AUTH_PROVIDERS:-none} wui_dispatch=$LDE_WUI_DISPATCH"
}

# _gde_cors <hub.env> -- SPOOL_HUB_VIEW_CORS_ORIGINS = cnf origins + the WUI
# origins in use (see do_gen_docker_env). Order kept, duplicates dropped.
_gde_cors() {
  local f="$1" cors o p sib extra=()
  cors="$(sed -n 's/^SPOOL_HUB_VIEW_CORS_ORIGINS=//p' "$f")"
  extra+=("http://localhost:$LDE_WUI_PORT")
  for sib in "$(dirname "$LDE_STATE_DIR")"/*/compose.env; do
    [[ -r "$sib" && "$sib" != "$LDE_COMPOSE_ENV" ]] || continue
    p="$(sed -n 's/^LDE_WUI_PORT=\([0-9]\{1,5\}\)$/\1/p' "$sib")"
    [[ -n "$p" ]] && extra+=("http://localhost:$p")
  done
  IFS=',' read -r -a o <<<"${LDE_WUI_EXTRA_ORIGINS:-}"
  for p in "${o[@]}"; do
    p="${p// /}"; [[ -z "$p" ]] && continue
    [[ "$p" =~ ^https?://[a-z0-9.-]+(:[0-9]{1,5})?$ ]] ||
      { do_log "FATAL LDE_WUI_EXTRA_ORIGINS entry '$p' must be http(s)://host[:port]"; return 1; }
    extra+=("$p")
  done
  for o in "${extra[@]}"; do
    [[ ",$cors," == *",$o,"* ]] || cors="${cors:+$cors,}$o"
  done
  _gde_set "$f" SPOOL_HUB_VIEW_CORS_ORIGINS "$cors"
}

# _gde_set <file> <KEY> <value> -- replace KEY's line, or append it.
_gde_set() {
  { grep -v "^$2=" "$1"; echo "$2=$3"; } >"$1.set" && mv -f "$1.set" "$1"
}

# _gde_ports <file> -- fill {lde_wui_port} / {lde_hub_port} with this tree's
# ports, so an LDE_WUI_PORT override moves APP_URL and the redirect URIs too.
_gde_ports() {
  local line
  while IFS= read -r line; do
    line="${line//\{lde_wui_port\}/$LDE_WUI_PORT}"
    printf '%s\n' "${line//\{lde_hub_port\}/$LDE_HUB_PORT}"
  done <"$1" >"$1.ports" && mv -f "$1.ports" "$1"
}

# _gde_switches <file> -- apply env.lde.switches (see the header).
_gde_switches() {
  local f="$1" on_off=(false true) p id secret
  _gde_set "$f" SPOOL_HUB_AUTH_NATIVE_ENABLED "${on_off[$LDE_AUTH_NATIVE]}" || return 1
  _gde_set "$f" SPOOL_HUB_AUTH_PROVIDERS "$LDE_AUTH_PROVIDERS" || return 1
  _gde_set "$f" SPOOL_HUB_WUI_DISPATCH "${on_off[$LDE_WUI_DISPATCH]}" || return 1
  _gde_set "$f" SPOOL_HUB_WUI_KEY_EPHEMERAL "${on_off[$LDE_WUI_DISPATCH]}" || return 1
  for p in ${LDE_AUTH_PROVIDERS//,/ }; do
    id="SPOOL_HUB_AUTH_${p^^}_CLIENT_ID" secret="SPOOL_HUB_AUTH_${p^^}_CLIENT_SECRET"
    [[ -n "${!id:-}" && -n "${!secret:-}" ]] || {
      do_log "FATAL LDE_AUTH_PROVIDERS lists $p: export $id and $secret (never in cnf)"; return 1; }
    _gde_set "$f" "$id" "${!id}" && _gde_set "$f" "$secret" "${!secret}" || return 1
  done
  if [[ -n "$LDE_AUTH_PROVIDERS" && -n "${SPOOL_HUB_AUTH_IDP_BASE_URL:-}" ]]; then
    _gde_set "$f" SPOOL_HUB_AUTH_IDP_BASE_URL "$SPOOL_HUB_AUTH_IDP_BASE_URL" || return 1
  fi
  [[ "$LDE_AUTH_NATIVE" == 1 || -n "$LDE_AUTH_PROVIDERS" ]] || return 0
  local key_file="$LDE_STATE_DIR/auth-session.key"
  if [[ ! -s "$key_file" ]]; then
    (umask 077; od -An -tx1 -N32 /dev/urandom | tr -d ' \n' >"$key_file") || return 1
  fi
  _gde_set "$f" SPOOL_HUB_AUTH_SESSION_KEY "$(<"$key_file")"
}
