-- GENERATED by csi-spl-api internal/store/stmt_print_test.go (TestHotStmtPrint); do not edit.
-- @@pub {lobby,alerts,feedback,issues,tasks}
-- @@stmt walk_all sha256=012051ab868b77663ab4215ea721e27ddaec0ee9a4ed43f2ac8b0415640b882a scope=walk exec=:'t',now(),:'r',:'pub',:'mine',:'lobby',51
-- @@scope SELECT set_config('app.tenant_id', $1, true), set_config('jit', 'off', true), set_config('enable_bitmapscan', 'off', true), set_config('plan_cache_mode', 'force_custom_plan', true), set_config('enable_sort', 'off', true)
WITH RECURSIVE w (task_id, received_at, n) AS (
			(SELECT l.task_id, l.received_at, 1 FROM messages l WHERE l.tenant_id = $1 AND l.expires_at > $2 AND (SELECT x.msg_id = l.msg_id FROM messages x WHERE x.tenant_id = $1 AND x.expires_at > $2 AND x.task_id = l.task_id
			ORDER BY x.received_at DESC, x.msg_id DESC LIMIT 1) AND (SELECT true FROM messages d WHERE d.tenant_id = $1 AND d.expires_at > $2 AND d.task_id = l.task_id AND (d.channel = ANY($4::text[]) OR d.channel = ANY($5::text[]) OR (d.channel IS NULL AND (d.from_id = $3 OR d.to_id = $3))) LIMIT 1) AND (SELECT f.parent_task_id IS NULL FROM messages f WHERE f.tenant_id = $1 AND f.expires_at > $2 AND f.task_id = l.task_id ORDER BY f.received_at, f.msg_id::text LIMIT 1) AND (SELECT true FROM issues i WHERE i.tenant_id = $1 AND i.task_id = l.task_id LIMIT 1) IS NULL AND NOT EXISTS (SELECT 1 FROM messages z WHERE z.tenant_id = $1 AND z.archived_at IS NOT NULL
		AND (z.msg_id = l.task_id OR (z.task_id = l.task_id AND l.task_id::text <> $6))) ORDER BY l.received_at DESC, l.task_id::text DESC LIMIT 1)
			UNION ALL
			SELECT s.task_id, s.received_at, w.n + 1 FROM w CROSS JOIN LATERAL (
				SELECT l.task_id, l.received_at FROM messages l
				WHERE l.tenant_id = $1 AND l.expires_at > $2 AND (SELECT x.msg_id = l.msg_id FROM messages x WHERE x.tenant_id = $1 AND x.expires_at > $2 AND x.task_id = l.task_id
			ORDER BY x.received_at DESC, x.msg_id DESC LIMIT 1) AND (SELECT true FROM messages d WHERE d.tenant_id = $1 AND d.expires_at > $2 AND d.task_id = l.task_id AND (d.channel = ANY($4::text[]) OR d.channel = ANY($5::text[]) OR (d.channel IS NULL AND (d.from_id = $3 OR d.to_id = $3))) LIMIT 1) AND (SELECT f.parent_task_id IS NULL FROM messages f WHERE f.tenant_id = $1 AND f.expires_at > $2 AND f.task_id = l.task_id ORDER BY f.received_at, f.msg_id::text LIMIT 1) AND (SELECT true FROM issues i WHERE i.tenant_id = $1 AND i.task_id = l.task_id LIMIT 1) IS NULL AND NOT EXISTS (SELECT 1 FROM messages z WHERE z.tenant_id = $1 AND z.archived_at IS NOT NULL
		AND (z.msg_id = l.task_id OR (z.task_id = l.task_id AND l.task_id::text <> $6))) AND l.received_at <= w.received_at
					AND (l.received_at, l.task_id::text) < (w.received_at, w.task_id::text) ORDER BY l.received_at DESC, l.task_id::text DESC LIMIT 1
			) s
			WHERE w.n < $7
		)
		SELECT w.task_id::text, f.channel, f.parent, f.first_at, w.received_at, a.n, a.kinds, a.parties, f.first_msg
		FROM w CROSS JOIN LATERAL (
			SELECT count(*)::int AS n,
				array_agg(m.kind ORDER BY m.received_at, m.msg_id::text) AS kinds,
				(SELECT array_agg(DISTINCT p ORDER BY p) FROM unnest(array_agg(m.from_id || '@' || m.from_box)
					|| array_agg(m.to_id || '@' || m.to_box)) p) AS parties
			FROM messages m
			WHERE m.tenant_id = $1 AND m.expires_at > $2 AND m.task_id = w.task_id AND (m.channel = ANY($4::text[]) OR m.channel = ANY($5::text[]) OR (m.channel IS NULL AND (m.from_id = $3 OR m.to_id = $3)))
		) a LEFT JOIN LATERAL (
			SELECT COALESCE(m.channel, '') AS channel, COALESCE(m.parent_task_id::text, '') AS parent,
				m.received_at AS first_at, (SELECT CASE WHEN jsonb_typeof(m.msg -> 'body') = 'string' THEN jsonb_build_object('body', left(s.a, 140) ||
		CASE WHEN ltrim(substr(s.a, 141), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000') = '' THEN ''
			ELSE left(substr(s.a, 141), char_length(substr(s.a, 141)) - char_length(ltrim(substr(s.a, 141), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000')) + 1) END)
		ELSE '{}'::jsonb END
		FROM (SELECT ltrim(split_part(m.msg ->> 'body', E'\n', 1), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000') AS a) s) AS first_msg
			FROM messages m
			WHERE m.tenant_id = $1 AND m.expires_at > $2 AND m.task_id = w.task_id AND (m.channel = ANY($4::text[]) OR m.channel = ANY($5::text[]) OR (m.channel IS NULL AND (m.from_id = $3 OR m.to_id = $3)))
			ORDER BY m.received_at, m.msg_id::text LIMIT 1
		) f ON true
		ORDER BY w.received_at DESC, w.task_id::text DESC
-- @@stmt walk_dm sha256=ffdbf43a5cae41eb2829d33d00cffce9bc8d83904b9e24aefa6a37ae2d135f84 scope=walk exec=:'t',now(),:'r',:'r',:'pub',:'mine',:'lobby',51
-- @@scope SELECT set_config('app.tenant_id', $1, true), set_config('jit', 'off', true), set_config('enable_bitmapscan', 'off', true), set_config('plan_cache_mode', 'force_custom_plan', true), set_config('enable_sort', 'off', true)
WITH RECURSIVE w (task_id, received_at, n) AS (
			(SELECT l.task_id, l.received_at, 1 FROM messages l WHERE l.tenant_id = $1 AND l.expires_at > $2 AND l.channel IS NULL AND (SELECT x.msg_id = l.msg_id FROM messages x WHERE x.tenant_id = $1 AND x.expires_at > $2 AND x.channel IS NULL AND x.task_id = l.task_id
			ORDER BY x.received_at DESC, x.msg_id DESC LIMIT 1) AND (SELECT true FROM messages v WHERE v.tenant_id = $1 AND v.expires_at > $2 AND v.channel IS NULL AND v.task_id = l.task_id AND (v.from_id = $3 OR v.to_id = $3) LIMIT 1) AND (SELECT true FROM messages d WHERE d.tenant_id = $1 AND d.expires_at > $2 AND d.channel IS NULL AND d.task_id = l.task_id AND (d.channel = ANY($5::text[]) OR d.channel = ANY($6::text[]) OR (d.channel IS NULL AND (d.from_id = $4 OR d.to_id = $4))) LIMIT 1) AND (SELECT f.parent_task_id IS NULL FROM messages f WHERE f.tenant_id = $1 AND f.expires_at > $2 AND f.channel IS NULL AND f.task_id = l.task_id ORDER BY f.received_at, f.msg_id::text LIMIT 1) AND (SELECT true FROM issues i WHERE i.tenant_id = $1 AND i.task_id = l.task_id LIMIT 1) IS NULL AND NOT EXISTS (SELECT 1 FROM messages z WHERE z.tenant_id = $1 AND z.archived_at IS NOT NULL
		AND (z.msg_id = l.task_id OR (z.task_id = l.task_id AND l.task_id::text <> $7))) ORDER BY l.received_at DESC, l.task_id::text DESC LIMIT 1)
			UNION ALL
			SELECT s.task_id, s.received_at, w.n + 1 FROM w CROSS JOIN LATERAL (
				SELECT l.task_id, l.received_at FROM messages l
				WHERE l.tenant_id = $1 AND l.expires_at > $2 AND l.channel IS NULL AND (SELECT x.msg_id = l.msg_id FROM messages x WHERE x.tenant_id = $1 AND x.expires_at > $2 AND x.channel IS NULL AND x.task_id = l.task_id
			ORDER BY x.received_at DESC, x.msg_id DESC LIMIT 1) AND (SELECT true FROM messages v WHERE v.tenant_id = $1 AND v.expires_at > $2 AND v.channel IS NULL AND v.task_id = l.task_id AND (v.from_id = $3 OR v.to_id = $3) LIMIT 1) AND (SELECT true FROM messages d WHERE d.tenant_id = $1 AND d.expires_at > $2 AND d.channel IS NULL AND d.task_id = l.task_id AND (d.channel = ANY($5::text[]) OR d.channel = ANY($6::text[]) OR (d.channel IS NULL AND (d.from_id = $4 OR d.to_id = $4))) LIMIT 1) AND (SELECT f.parent_task_id IS NULL FROM messages f WHERE f.tenant_id = $1 AND f.expires_at > $2 AND f.channel IS NULL AND f.task_id = l.task_id ORDER BY f.received_at, f.msg_id::text LIMIT 1) AND (SELECT true FROM issues i WHERE i.tenant_id = $1 AND i.task_id = l.task_id LIMIT 1) IS NULL AND NOT EXISTS (SELECT 1 FROM messages z WHERE z.tenant_id = $1 AND z.archived_at IS NOT NULL
		AND (z.msg_id = l.task_id OR (z.task_id = l.task_id AND l.task_id::text <> $7))) AND l.received_at <= w.received_at
					AND (l.received_at, l.task_id::text) < (w.received_at, w.task_id::text) ORDER BY l.received_at DESC, l.task_id::text DESC LIMIT 1
			) s
			WHERE w.n < $8
		)
		SELECT w.task_id::text, f.channel, f.parent, f.first_at, w.received_at, a.n, a.kinds, a.parties, f.first_msg
		FROM w CROSS JOIN LATERAL (
			SELECT count(*)::int AS n,
				array_agg(m.kind ORDER BY m.received_at, m.msg_id::text) AS kinds,
				(SELECT array_agg(DISTINCT p ORDER BY p) FROM unnest(array_agg(m.from_id || '@' || m.from_box)
					|| array_agg(m.to_id || '@' || m.to_box)) p) AS parties
			FROM messages m
			WHERE m.tenant_id = $1 AND m.expires_at > $2 AND m.channel IS NULL AND m.task_id = w.task_id AND (m.channel = ANY($5::text[]) OR m.channel = ANY($6::text[]) OR (m.channel IS NULL AND (m.from_id = $4 OR m.to_id = $4)))
		) a LEFT JOIN LATERAL (
			SELECT COALESCE(m.channel, '') AS channel, COALESCE(m.parent_task_id::text, '') AS parent,
				m.received_at AS first_at, (SELECT CASE WHEN jsonb_typeof(m.msg -> 'body') = 'string' THEN jsonb_build_object('body', left(s.a, 140) ||
		CASE WHEN ltrim(substr(s.a, 141), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000') = '' THEN ''
			ELSE left(substr(s.a, 141), char_length(substr(s.a, 141)) - char_length(ltrim(substr(s.a, 141), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000')) + 1) END)
		ELSE '{}'::jsonb END
		FROM (SELECT ltrim(split_part(m.msg ->> 'body', E'\n', 1), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000') AS a) s) AS first_msg
			FROM messages m
			WHERE m.tenant_id = $1 AND m.expires_at > $2 AND m.channel IS NULL AND m.task_id = w.task_id AND (m.channel = ANY($5::text[]) OR m.channel = ANY($6::text[]) OR (m.channel IS NULL AND (m.from_id = $4 OR m.to_id = $4)))
			ORDER BY m.received_at, m.msg_id::text LIMIT 1
		) f ON true
		ORDER BY w.received_at DESC, w.task_id::text DESC
-- @@stmt thread sha256=fc1119860f1d66dbae23ec05e8f6fe55853b6271beb53994035ed6eb82788c85 scope=tenant exec=:'t',:'task',now(),NULL,'',51,NULL,'',:'r',:'pub',:'mine'
-- @@scope SELECT set_config('app.tenant_id', $1, true)
SELECT msg_id::text, received_at, env, edited_at, edited_by,
				CASE WHEN edited_at IS NULL THEN 0 ELSE COALESCE((SELECT MAX(revision)
					FROM message_revisions r WHERE r.tenant_id = messages.tenant_id AND r.msg_id = messages.msg_id), 0) END,
				is_parent, typed_by, responsible, ref_task_id::text, mirror_of::text, kind, kind_set_at, kind_set_by, moved_at, moved_by, moved_from_channel, moved_from_task::text, channel, task_id::text, parent_task_id::text
			FROM messages
			WHERE tenant_id = $1 AND task_id = $2::uuid AND expires_at > $3
				AND ($4::timestamptz IS NULL OR (received_at, msg_id::text) > ($4::timestamptz, $5::text))
				AND ($7::timestamptz IS NULL OR (received_at, msg_id::text) < ($7::timestamptz, $8::text))
				AND ((channel IS NULL AND (from_id = $9 OR to_id = $9))
			OR channel = ANY($10::text[]) OR channel = ANY($11::text[]))
			ORDER BY received_at DESC, msg_id::text DESC
			LIMIT $6
-- @@stmt flow_counts sha256=62d1cf0828d344e4826910dd8859ed006afadb8d90fada2070bb3a5d51314c6f scope=tenant exec=:'t',:'r',now(),:'pub',:'lobby'
-- @@scope SELECT set_config('app.tenant_id', $1, true)
WITH RECURSIVE fp(k) AS (SELECT min(x.place_key) FROM flow_events x WHERE x.tenant_id = $1 AND x.member_id = $2
			UNION ALL SELECT (SELECT min(x.place_key) FROM flow_events x WHERE x.tenant_id = $1 AND x.member_id = $2 AND x.place_key > fp.k)
			FROM fp WHERE fp.k IS NOT NULL),
		ft AS (SELECT fe.* FROM fp
			CROSS JOIN LATERAL (SELECT coalesce(max(r.at), '-infinity'::timestamptz) AS at FROM read_marks r WHERE r.tenant_id = $1 AND r.member_id = $2
				AND r.mark_key IN (fp.k, CASE WHEN fp.k LIKE 'dm:%@%' THEN regexp_replace(fp.k, '@[^@]*$', '') END)) fb
			CROSS JOIN LATERAL (SELECT fe.tenant_id, fe.member_id, fe.msg_id, fe.kind, fe.at, fe.expires_at FROM flow_events fe
				WHERE fe.tenant_id = $1 AND fe.member_id = $2 AND fe.place_key = fp.k
				AND fe.cov_at >= fb.at OFFSET 0) fe
			WHERE fp.k IS NOT NULL
			UNION ALL SELECT fe.tenant_id, fe.member_id, fe.msg_id, fe.kind, fe.at, fe.expires_at FROM flow_events fe
			WHERE fe.tenant_id = $1 AND fe.member_id = $2 AND (fe.place_key IS NULL OR fe.cov_at IS NULL)),
		fc AS (SELECT fe.kind, fm.channel IS NOT NULL AS in_ch,
				CASE WHEN fm.channel IS NOT NULL THEN 'ch:' || fm.channel
					WHEN coalesce(fm.from_box, '') <> '' THEN 'dm:' || fm.from_id || '@' || fm.from_box
					ELSE 'dm:' || fm.from_id END AS place_key,
				't:' || fm.task_id::text AS topic_key,
				fe.at > coalesce((SELECT s.at FROM read_marks s
				WHERE s.tenant_id = $1 AND s.member_id = $2 AND s.mark_key = 'f:seen'), '-infinity'::timestamptz) AS unseen
			FROM ft fe CROSS JOIN LATERAL (SELECT fm.channel, fm.from_box, fm.from_id, fm.to_id, fm.task_id, fm.parent_task_id, fm.msg_id, fm.received_at, fm.expires_at FROM messages fm WHERE fm.tenant_id = fe.tenant_id AND fm.msg_id = fe.msg_id LIMIT 1) fm
			WHERE fe.expires_at > $3 AND fm.expires_at > $3 AND CASE WHEN fm.channel IS NULL THEN fe.member_id IN (fm.to_id, fm.from_id)
		WHEN fm.channel = ANY($4::text[]) THEN true
		ELSE EXISTS (SELECT 1 FROM channel_humans h WHERE h.tenant_id = fe.tenant_id AND h.channel_id = fm.channel AND h.human_id = fe.member_id)
			AND NOT EXISTS (SELECT 1 FROM channels dc WHERE dc.tenant_id = fe.tenant_id AND dc.channel_id = fm.channel AND dc.archived_at IS NOT NULL) END AND NOT (NOT (true AND NOT EXISTS (SELECT 1 FROM messages z WHERE z.tenant_id = fe.tenant_id AND z.archived_at IS NOT NULL
		AND (z.msg_id = fm.msg_id OR z.msg_id = fm.task_id
			OR (z.task_id = fm.task_id AND fm.task_id::text <> $5::text)
			OR (z.task_id = fm.parent_task_id AND fm.parent_task_id::text <> $5::text)))) OR EXISTS (SELECT 1 FROM read_marks r WHERE r.tenant_id = fe.tenant_id AND r.member_id = fe.member_id AND r.mark_key = 'f:' || fe.msg_id::text)
		OR EXISTS (SELECT 1 FROM read_marks r WHERE r.tenant_id = fe.tenant_id AND r.member_id = fe.member_id
			AND r.mark_key IN ('t:' || fm.task_id::text,
				CASE WHEN fm.channel IS NULL THEN 'dm:' || fm.from_id ELSE 'ch:' || fm.channel END,
				CASE WHEN fm.channel IS NULL THEN 'dm:' || fm.from_id || '@' || fm.from_box END)
			AND (fm.received_at, fm.msg_id::text) <= (r.at, r.msg_id))))
		SELECT count(*) FILTER (WHERE fc.unseen AND fc.kind IN ('mention', 'poke')),
			count(*) FILTER (WHERE fc.unseen AND fc.kind = 'reply'),
			count(*) FILTER (WHERE fc.unseen AND fc.kind = 'dm'),
			count(*) FILTER (WHERE fc.unseen AND fc.in_ch),
			count(*) FILTER (WHERE fc.unseen AND NOT fc.in_ch),
			count(*) FILTER (WHERE fc.kind IN ('mention', 'poke')),
			count(*) FILTER (WHERE fc.kind = 'reply'),
			count(*) FILTER (WHERE fc.kind = 'dm'),
			count(*) FILTER (WHERE fc.in_ch),
			count(*) FILTER (WHERE NOT fc.in_ch),
			(SELECT coalesce(jsonb_object_agg(k.key, k.n), '{}'::jsonb) FROM (SELECT x.key, count(*) AS n
				FROM fc f2 CROSS JOIN LATERAL (VALUES (f2.place_key), (f2.topic_key)) x(key) GROUP BY x.key) k)
		FROM fc
-- @@stmt ch_counts sha256=281950a58d20ba4abcf87248ea217f26c5ec18e1d69e9fbb1e1cf6af33536437 scope=tenant exec=:'t',now(),:'r'
-- @@scope SELECT set_config('app.tenant_id', $1, true)
WITH c AS (
			SELECT channel, count(*)::int AS n, max(received_at) AS last_at, count(DISTINCT from_id)::int AS posters,
				count(*) FILTER (WHERE $3::text IS NULL OR from_id IS DISTINCT FROM $3)::int AS others
			FROM messages WHERE tenant_id = $1 AND channel IS NOT NULL AND expires_at > $2
			GROUP BY channel)
		SELECT c.channel, c.n, c.last_at, l.msg_id, c.posters, c.others FROM c
		CROSS JOIN LATERAL (SELECT x.msg_id::text AS msg_id FROM messages x
			WHERE x.tenant_id = $1 AND x.channel = c.channel AND x.expires_at > $2 AND x.received_at = c.last_at
			ORDER BY x.msg_id::text DESC LIMIT 1) l
-- @@stmt ch_marked sha256=a97c1ff9ead4e6e7608d811dea94f0fd244cf0664f99fe2b605e9457d1653b22 scope=tenant exec=:'t',now(),'{}','{}','{}',:'r',:'lobby'
-- @@scope SELECT set_config('app.tenant_id', $1, true)
WITH pm AS (SELECT u.ch, u.at, u.id FROM unnest($3::text[], $4::timestamptz[], $5::text[]) AS u(ch, at, id)),
		sm AS (SELECT substr(mark_key, 4) AS ch, at, msg_id AS id FROM read_marks
			WHERE $6::text IS NOT NULL AND tenant_id = $1 AND member_id = $6 AND mark_key LIKE 'ch:%'),
		mk AS (SELECT DISTINCT ON (ch) ch, at, id FROM (SELECT ch, at, id FROM pm UNION ALL SELECT ch, at, id FROM sm) x ORDER BY ch, at DESC, id DESC)
		SELECT mk.ch, c.n FROM mk CROSS JOIN LATERAL (SELECT count(*)::int AS n FROM messages m
			WHERE m.tenant_id = $1 AND m.channel = mk.ch AND m.expires_at > $2
			AND m.received_at >= mk.at AND (m.received_at, m.msg_id::text) > (mk.at, mk.id)
			AND ($6::text IS NULL OR (m.from_id IS DISTINCT FROM $6 AND m.typed_by IS DISTINCT FROM $6)) AND ($6::text IS NULL OR NOT EXISTS (SELECT 1 FROM read_marks tm WHERE tm.tenant_id = $1 AND tm.member_id = $6
		AND tm.mark_key = 't:' || m.task_id::text AND (m.received_at, m.msg_id::text) <= (tm.at, tm.msg_id))) AND NOT EXISTS (SELECT 1 FROM messages z WHERE z.tenant_id = $1 AND z.archived_at IS NOT NULL
		AND (z.msg_id = m.msg_id OR z.msg_id = m.task_id
			OR (z.task_id = m.task_id AND m.task_id::text <> $7)
			OR (z.task_id = m.parent_task_id AND m.parent_task_id::text <> $7)))) c
-- @@stmt ch_hidden sha256=789f59de2630a1737ed1cae7f90086b4b47d1670bc15196224bc9e235c914180 scope=tenant exec=:'t',now(),'{}','{}','{}',:'r',:'lobby','{issues,tasks}'
-- @@scope SELECT set_config('app.tenant_id', $1, true)
WITH RECURSIVE pm AS (SELECT u.ch, u.at, u.id FROM unnest($3::text[], $4::timestamptz[], $5::text[]) AS u(ch, at, id)),
		sm AS (SELECT substr(mark_key, 4) AS ch, at, msg_id AS id FROM read_marks
			WHERE $6::text IS NOT NULL AND tenant_id = $1 AND member_id = $6 AND mark_key LIKE 'ch:%'),
		mk AS (SELECT DISTINCT ON (ch) ch, at, id FROM (SELECT ch, at, id FROM pm UNION ALL SELECT ch, at, id FROM sm) x ORDER BY ch, at DESC, id DESC),
		cl AS (SELECT (SELECT min(channel) FROM messages WHERE tenant_id = $1 AND channel IS NOT NULL) AS ch
			UNION ALL SELECT (SELECT min(x.channel) FROM messages x WHERE x.tenant_id = $1 AND x.channel > cl.ch) FROM cl WHERE cl.ch IS NOT NULL),
		um AS (SELECT 1 FROM cl WHERE cl.ch IS NOT NULL AND NOT EXISTS (SELECT 1 FROM mk WHERE mk.ch = cl.ch)
			AND cl.ch <> ALL($8::text[]) AND NOT EXISTS (SELECT 1 FROM channels dc WHERE dc.tenant_id = $1 AND dc.channel_id = cl.ch AND dc.archived_at IS NOT NULL)
			AND (SELECT true FROM messages a WHERE a.tenant_id = $1 AND a.archived_at IS NOT NULL LIMIT 1)
			AND (SELECT true FROM messages u WHERE u.tenant_id = $1 AND u.channel = cl.ch AND u.expires_at > $2
				AND ($6::text IS NULL OR u.from_id IS DISTINCT FROM $6) AND (u.archived_at IS NOT NULL OR EXISTS (SELECT 1 FROM messages z WHERE z.tenant_id = $1 AND z.archived_at IS NOT NULL
					AND (z.msg_id = u.task_id OR (z.task_id = u.task_id AND u.task_id::text <> $7)
						OR (z.task_id = u.parent_task_id AND u.parent_task_id::text <> $7)))) LIMIT 1) LIMIT 1),
		z AS (SELECT msg_id, task_id FROM messages WHERE tenant_id = $1 AND archived_at IS NOT NULL AND EXISTS (SELECT 1 FROM um)),
		h AS (
			SELECT m.msg_id, m.channel, m.from_id, m.expires_at FROM z JOIN messages m ON m.tenant_id = $1 AND m.msg_id = z.msg_id AND m.channel IS NOT NULL AND NOT EXISTS (SELECT 1 FROM mk WHERE mk.ch = m.channel)
			UNION SELECT m.msg_id, m.channel, m.from_id, m.expires_at FROM z JOIN messages m ON m.tenant_id = $1 AND m.task_id = z.msg_id AND m.channel IS NOT NULL AND NOT EXISTS (SELECT 1 FROM mk WHERE mk.ch = m.channel)
			UNION SELECT m.msg_id, m.channel, m.from_id, m.expires_at FROM z JOIN messages m ON m.tenant_id = $1 AND m.task_id = z.task_id AND z.task_id::text <> $7 AND m.channel IS NOT NULL AND NOT EXISTS (SELECT 1 FROM mk WHERE mk.ch = m.channel)
			UNION SELECT m.msg_id, m.channel, m.from_id, m.expires_at FROM z JOIN messages m ON m.tenant_id = $1 AND m.parent_task_id = z.task_id AND z.task_id::text <> $7 AND m.channel IS NOT NULL AND NOT EXISTS (SELECT 1 FROM mk WHERE mk.ch = m.channel))
		SELECT h.channel, count(*)::int FROM h
		WHERE h.expires_at > $2 AND ($6::text IS NULL OR h.from_id IS DISTINCT FROM $6)
		GROUP BY h.channel
-- @@stmt walk_all_head sha256=fa0ce858ac08daf8ad1a5268a2dce1941774ac7bda5f6160a0dc350abd81f48b scope=head exec=:'t',now(),:'r',:'pub',:'mine',:'lobby',51
-- @@scope SELECT set_config('app.tenant_id', $1, true), set_config('jit', 'off', true), set_config('plan_cache_mode', 'force_custom_plan', true), set_config('enable_bitmapscan', 'on', true), set_config('enable_sort', 'on', true)
WITH w (task_id, received_at) AS (
			SELECT l.task_id, l.last_at FROM topic_heads l
			WHERE l.tenant_id = $1 AND l.valid_until > $2 AND EXISTS (SELECT 1 FROM topic_head_parts d WHERE d.tenant_id = $1 AND d.task_id = l.task_id AND (d.channel = ANY($4::text[]) OR d.channel = ANY($5::text[]) OR (d.channel IS NULL AND (d.dm_a = $3 OR d.dm_b = $3)))) AND NOT l.card_archived AND (l.archived_rows = 0 OR l.task_id::text = $6) AND (SELECT f.parent_task_id IS NULL FROM messages f WHERE f.tenant_id = $1 AND f.expires_at > $2 AND f.task_id = l.task_id ORDER BY f.received_at, f.msg_id::text LIMIT 1) AND (SELECT true FROM issues i WHERE i.tenant_id = $1 AND i.task_id = l.task_id LIMIT 1) IS NULL
			ORDER BY l.last_at DESC, l.task_id DESC LIMIT $7
		)
		SELECT w.task_id::text, f.channel, f.parent, f.first_at, w.received_at, a.n, a.kinds, a.parties, f.first_msg
		FROM w CROSS JOIN LATERAL (
			SELECT count(*)::int AS n,
				array_agg(m.kind ORDER BY m.received_at, m.msg_id::text) AS kinds,
				(SELECT array_agg(DISTINCT p ORDER BY p) FROM unnest(array_agg(m.from_id || '@' || m.from_box)
					|| array_agg(m.to_id || '@' || m.to_box)) p) AS parties
			FROM messages m
			WHERE m.tenant_id = $1 AND m.expires_at > $2 AND m.task_id = w.task_id AND (m.channel = ANY($4::text[]) OR m.channel = ANY($5::text[]) OR (m.channel IS NULL AND (m.from_id = $3 OR m.to_id = $3)))
		) a LEFT JOIN LATERAL (
			SELECT COALESCE(m.channel, '') AS channel, COALESCE(m.parent_task_id::text, '') AS parent,
				m.received_at AS first_at, (SELECT CASE WHEN jsonb_typeof(m.msg -> 'body') = 'string' THEN jsonb_build_object('body', left(s.a, 140) ||
		CASE WHEN ltrim(substr(s.a, 141), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000') = '' THEN ''
			ELSE left(substr(s.a, 141), char_length(substr(s.a, 141)) - char_length(ltrim(substr(s.a, 141), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000')) + 1) END)
		ELSE '{}'::jsonb END
		FROM (SELECT ltrim(split_part(m.msg ->> 'body', E'\n', 1), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000') AS a) s) AS first_msg
			FROM messages m
			WHERE m.tenant_id = $1 AND m.expires_at > $2 AND m.task_id = w.task_id AND (m.channel = ANY($4::text[]) OR m.channel = ANY($5::text[]) OR (m.channel IS NULL AND (m.from_id = $3 OR m.to_id = $3)))
			ORDER BY m.received_at, m.msg_id::text LIMIT 1
		) f ON true
		ORDER BY w.received_at DESC, w.task_id::text DESC
-- @@stmt walk_dm_head sha256=a58f9b835a0e50787b95e5d745b082826cfdcb6a034194df1c2e4fbea9f0da3b scope=head exec=:'t',now(),:'r',:'pub',:'mine',:'lobby',51
-- @@scope SELECT set_config('app.tenant_id', $1, true), set_config('jit', 'off', true), set_config('plan_cache_mode', 'force_custom_plan', true), set_config('enable_bitmapscan', 'on', true), set_config('enable_sort', 'on', true)
WITH w (task_id, received_at) AS (
			SELECT l.task_id, l.dm_last_at FROM topic_heads l
			WHERE l.tenant_id = $1 AND l.dm_last_at IS NOT NULL AND l.valid_until > $2 AND EXISTS (SELECT 1 FROM topic_head_parts d WHERE d.tenant_id = $1 AND d.task_id = l.task_id AND ((d.channel IS NULL AND (d.dm_a = $3 OR d.dm_b = $3)))) AND NOT l.card_archived AND (l.archived_rows = 0 OR l.task_id::text = $6) AND (SELECT f.parent_task_id IS NULL FROM messages f WHERE f.tenant_id = $1 AND f.expires_at > $2 AND f.channel IS NULL AND f.task_id = l.task_id ORDER BY f.received_at, f.msg_id::text LIMIT 1) AND (SELECT true FROM issues i WHERE i.tenant_id = $1 AND i.task_id = l.task_id LIMIT 1) IS NULL
			ORDER BY l.dm_last_at DESC, l.task_id DESC LIMIT $7
		)
		SELECT w.task_id::text, f.channel, f.parent, f.first_at, w.received_at, a.n, a.kinds, a.parties, f.first_msg
		FROM w CROSS JOIN LATERAL (
			SELECT count(*)::int AS n,
				array_agg(m.kind ORDER BY m.received_at, m.msg_id::text) AS kinds,
				(SELECT array_agg(DISTINCT p ORDER BY p) FROM unnest(array_agg(m.from_id || '@' || m.from_box)
					|| array_agg(m.to_id || '@' || m.to_box)) p) AS parties
			FROM messages m
			WHERE m.tenant_id = $1 AND m.expires_at > $2 AND m.channel IS NULL AND m.task_id = w.task_id AND (m.channel = ANY($4::text[]) OR m.channel = ANY($5::text[]) OR (m.channel IS NULL AND (m.from_id = $3 OR m.to_id = $3)))
		) a LEFT JOIN LATERAL (
			SELECT COALESCE(m.channel, '') AS channel, COALESCE(m.parent_task_id::text, '') AS parent,
				m.received_at AS first_at, (SELECT CASE WHEN jsonb_typeof(m.msg -> 'body') = 'string' THEN jsonb_build_object('body', left(s.a, 140) ||
		CASE WHEN ltrim(substr(s.a, 141), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000') = '' THEN ''
			ELSE left(substr(s.a, 141), char_length(substr(s.a, 141)) - char_length(ltrim(substr(s.a, 141), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000')) + 1) END)
		ELSE '{}'::jsonb END
		FROM (SELECT ltrim(split_part(m.msg ->> 'body', E'\n', 1), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000') AS a) s) AS first_msg
			FROM messages m
			WHERE m.tenant_id = $1 AND m.expires_at > $2 AND m.channel IS NULL AND m.task_id = w.task_id AND (m.channel = ANY($4::text[]) OR m.channel = ANY($5::text[]) OR (m.channel IS NULL AND (m.from_id = $3 OR m.to_id = $3)))
			ORDER BY m.received_at, m.msg_id::text LIMIT 1
		) f ON true
		ORDER BY w.received_at DESC, w.task_id::text DESC
-- @@stmt walk_dm_head_worst sha256=a58f9b835a0e50787b95e5d745b082826cfdcb6a034194df1c2e4fbea9f0da3b scope=head exec=:'t',now(),:'w',:'pub',:'wmine',:'lobby',51
-- @@scope SELECT set_config('app.tenant_id', $1, true), set_config('jit', 'off', true), set_config('plan_cache_mode', 'force_custom_plan', true), set_config('enable_bitmapscan', 'on', true), set_config('enable_sort', 'on', true)
WITH w (task_id, received_at) AS (
			SELECT l.task_id, l.dm_last_at FROM topic_heads l
			WHERE l.tenant_id = $1 AND l.dm_last_at IS NOT NULL AND l.valid_until > $2 AND EXISTS (SELECT 1 FROM topic_head_parts d WHERE d.tenant_id = $1 AND d.task_id = l.task_id AND ((d.channel IS NULL AND (d.dm_a = $3 OR d.dm_b = $3)))) AND NOT l.card_archived AND (l.archived_rows = 0 OR l.task_id::text = $6) AND (SELECT f.parent_task_id IS NULL FROM messages f WHERE f.tenant_id = $1 AND f.expires_at > $2 AND f.channel IS NULL AND f.task_id = l.task_id ORDER BY f.received_at, f.msg_id::text LIMIT 1) AND (SELECT true FROM issues i WHERE i.tenant_id = $1 AND i.task_id = l.task_id LIMIT 1) IS NULL
			ORDER BY l.dm_last_at DESC, l.task_id DESC LIMIT $7
		)
		SELECT w.task_id::text, f.channel, f.parent, f.first_at, w.received_at, a.n, a.kinds, a.parties, f.first_msg
		FROM w CROSS JOIN LATERAL (
			SELECT count(*)::int AS n,
				array_agg(m.kind ORDER BY m.received_at, m.msg_id::text) AS kinds,
				(SELECT array_agg(DISTINCT p ORDER BY p) FROM unnest(array_agg(m.from_id || '@' || m.from_box)
					|| array_agg(m.to_id || '@' || m.to_box)) p) AS parties
			FROM messages m
			WHERE m.tenant_id = $1 AND m.expires_at > $2 AND m.channel IS NULL AND m.task_id = w.task_id AND (m.channel = ANY($4::text[]) OR m.channel = ANY($5::text[]) OR (m.channel IS NULL AND (m.from_id = $3 OR m.to_id = $3)))
		) a LEFT JOIN LATERAL (
			SELECT COALESCE(m.channel, '') AS channel, COALESCE(m.parent_task_id::text, '') AS parent,
				m.received_at AS first_at, (SELECT CASE WHEN jsonb_typeof(m.msg -> 'body') = 'string' THEN jsonb_build_object('body', left(s.a, 140) ||
		CASE WHEN ltrim(substr(s.a, 141), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000') = '' THEN ''
			ELSE left(substr(s.a, 141), char_length(substr(s.a, 141)) - char_length(ltrim(substr(s.a, 141), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000')) + 1) END)
		ELSE '{}'::jsonb END
		FROM (SELECT ltrim(split_part(m.msg ->> 'body', E'\n', 1), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000') AS a) s) AS first_msg
			FROM messages m
			WHERE m.tenant_id = $1 AND m.expires_at > $2 AND m.channel IS NULL AND m.task_id = w.task_id AND (m.channel = ANY($4::text[]) OR m.channel = ANY($5::text[]) OR (m.channel IS NULL AND (m.from_id = $3 OR m.to_id = $3)))
			ORDER BY m.received_at, m.msg_id::text LIMIT 1
		) f ON true
		ORDER BY w.received_at DESC, w.task_id::text DESC
-- @@stmt walk_parent_head sha256=a2e8ec33a6ad3dde5b82e4b6d2a281854859e59fb4779786d1f44d5164d3222a scope=head exec=:'t',now(),:'r',:'pub',:'mine','',:'parent',51
-- @@scope SELECT set_config('app.tenant_id', $1, true), set_config('jit', 'off', true), set_config('plan_cache_mode', 'force_custom_plan', true), set_config('enable_bitmapscan', 'on', true), set_config('enable_sort', 'on', true)
WITH w (task_id, received_at) AS (
			SELECT l.task_id, l.last_at FROM topic_heads l
			WHERE l.tenant_id = $1 AND l.valid_until > $2 AND EXISTS (SELECT 1 FROM topic_head_parts d WHERE d.tenant_id = $1 AND d.task_id = l.task_id AND (d.channel = ANY($4::text[]) OR d.channel = ANY($5::text[]) OR (d.channel IS NULL AND (d.dm_a = $3 OR d.dm_b = $3)))) AND NOT l.card_archived AND (l.archived_rows = 0 OR l.task_id::text = $6) AND l.task_id IN (SELECT p.task_id FROM messages p WHERE p.tenant_id = $1 AND p.parent_task_id = $7::uuid) AND (SELECT f.parent_task_id IS NOT DISTINCT FROM $7::uuid FROM messages f WHERE f.tenant_id = $1 AND f.expires_at > $2 AND f.task_id = l.task_id ORDER BY f.received_at, f.msg_id::text LIMIT 1)
			ORDER BY l.last_at DESC, l.task_id DESC LIMIT $8
		)
		SELECT w.task_id::text, f.channel, f.parent, f.first_at, w.received_at, a.n, a.kinds, a.parties, f.first_msg
		FROM w CROSS JOIN LATERAL (
			SELECT count(*)::int AS n,
				array_agg(m.kind ORDER BY m.received_at, m.msg_id::text) AS kinds,
				(SELECT array_agg(DISTINCT p ORDER BY p) FROM unnest(array_agg(m.from_id || '@' || m.from_box)
					|| array_agg(m.to_id || '@' || m.to_box)) p) AS parties
			FROM messages m
			WHERE m.tenant_id = $1 AND m.expires_at > $2 AND m.task_id = w.task_id AND (m.channel = ANY($4::text[]) OR m.channel = ANY($5::text[]) OR (m.channel IS NULL AND (m.from_id = $3 OR m.to_id = $3)))
		) a LEFT JOIN LATERAL (
			SELECT COALESCE(m.channel, '') AS channel, COALESCE(m.parent_task_id::text, '') AS parent,
				m.received_at AS first_at, (SELECT CASE WHEN jsonb_typeof(m.msg -> 'body') = 'string' THEN jsonb_build_object('body', left(s.a, 140) ||
		CASE WHEN ltrim(substr(s.a, 141), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000') = '' THEN ''
			ELSE left(substr(s.a, 141), char_length(substr(s.a, 141)) - char_length(ltrim(substr(s.a, 141), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000')) + 1) END)
		ELSE '{}'::jsonb END
		FROM (SELECT ltrim(split_part(m.msg ->> 'body', E'\n', 1), E'\t\n\u000B\f\r \u0085\u00A0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200A\u2028\u2029\u202F\u205F\u3000') AS a) s) AS first_msg
			FROM messages m
			WHERE m.tenant_id = $1 AND m.expires_at > $2 AND m.task_id = w.task_id AND (m.channel = ANY($4::text[]) OR m.channel = ANY($5::text[]) OR (m.channel IS NULL AND (m.from_id = $3 OR m.to_id = $3)))
			ORDER BY m.received_at, m.msg_id::text LIMIT 1
		) f ON true
		ORDER BY w.received_at DESC, w.task_id::text DESC
