package store

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"testing"
	"time"
)

// The hot statements do_spl_db_hot_measure runs (api perf round ap-00, t1
// ea9dc09a), printed by the store's OWN builders: the walks (viewTopicsSQL as
// handleViewTopics calls it), the topic page (newTopicPage), the Flow counts
// (flowCountsSQL as FlowRead calls it) and the three channel reads of
// ViewChannelStats. The action used to keep a hand copy of the walk frozen at
// SPL-984, and it measured 22 ms where the store's text took 114..286 ms.
//
// The printed copy is csi-spl-orc/src/bash/run/spl-db-hot-measure.stmt.sql.
// TestHotStmtCopyCurrent goes red when a builder changes and the copy does
// not; regenerate it with:
//
//	SPL_STMT_PRINT=<repo>/csi-spl-orc/src/bash/run/spl-db-hot-measure.stmt.sql \
//	  go test -run '^TestHotStmtPrint$' ./internal/store/
//
// Each statement is three parts, all read by the action:
//
//	-- @@stmt <name> sha256=<sha256 of the body> scope=<walk|tenant> exec=<EXECUTE args>
//	-- @@scope <the scope statement the hub sends first in the batch>
//	<the body, byte for byte the builder's text>
//
// The EXECUTE args are psql expressions: :'t' tenant, :'r' reader, :'pub' the
// public channels (the copy's "-- @@pub" line), :'mine' the reader's channels, :'lobby' the lobby task,
// :'task' the tenant's biggest topic, now() the clock.

// hotStmtCopy is the copy's path, from this package's directory.
const hotStmtCopy = "../../../../../../csi-spl-orc/src/bash/run/spl-db-hot-measure.stmt.sql"

// The sentinel argument values, each mapped back to its psql variable.
const (
	hotTenant = "@@t"
	hotReader = "@@r"
	hotLobby  = "@@lobby"
	hotTask   = "@@task"
	hotMine   = "@@mine"
)

var stmtNow = time.Date(2001, 2, 3, 4, 5, 6, 0, time.UTC)

type hotStmt struct {
	name, scope string
	sql         string
	args        []any
}

// hotStmts are the statements in the order the action measures them.
func hotStmts() []hotStmt {
	mine := []string{hotMine}
	walk := TopicQuery{Roots: true, NoIssues: true, Reader: hotReader, ReaderChannels: mine, Lobby: hotLobby, Limit: 51, Now: stmtNow}
	dm := walk
	dm.DM, dm.Viewer = true, hotReader // handleViewTopics: dm=true sets Viewer to the reader
	var out []hotStmt
	for _, w := range []struct {
		name string
		q    TopicQuery
	}{{"walk_all", walk}, {"walk_dm", dm}} {
		sql, args := viewTopicsSQL(hotTenant, w.q)
		out = append(out, hotStmt{w.name, pgScopeTenantNoJIT, sql, args})
	}
	page := newTopicPage(hotTenant, TopicMsgQuery{TaskID: hotTask, Desc: true, Reader: hotReader, ReaderChannels: mine, Limit: 51, Now: stmtNow})
	out = append(out, hotStmt{"thread", pgScopeTenant, page.read.sql, page.read.args})
	// FlowRead's counts read, with FlowRead's arguments.
	out = append(out, hotStmt{"flow_counts", pgScopeTenant, flowCountsSQL("$1", "$2", "$3", "$4::text[]", "$5::text"),
		[]any{hotTenant, hotReader, stmtNow, PublicChannels, hotLobby}})
	// ViewChannelStats' reads; no read= cursor, so the marks are the reader's stored ones.
	cs := newChannelStats(hotTenant)
	for _, r := range []struct {
		name string
		read tenantRead
	}{
		{"ch_counts", cs.countsRead(stmtNow, hotReader)},
		{"ch_marked", cs.markedUnreadRead(map[string]ReadMark{}, stmtNow, hotReader, hotLobby)},
		{"ch_hidden", cs.hiddenUnreadRead(map[string]ReadMark{}, stmtNow, hotReader, hotLobby)},
	} {
		out = append(out, hotStmt{r.name, pgScopeTenant, r.read.sql, r.read.args})
	}
	return out
}

// hotArg is the psql expression the action passes for builder argument v.
func hotArg(v any) (string, error) {
	switch x := v.(type) {
	case nil:
		return "NULL", nil
	case *time.Time:
		if x == nil {
			return "NULL", nil
		}
	case time.Time:
		if x.Equal(stmtNow) {
			return "now()", nil
		}
	case int:
		return strconv.Itoa(x), nil
	case string:
		switch x {
		case hotTenant:
			return ":'t'", nil
		case hotReader:
			return ":'r'", nil
		case hotLobby:
			return ":'lobby'", nil
		case hotTask:
			return ":'task'", nil
		case "":
			return "''", nil
		}
	case []string:
		switch {
		case reflect.DeepEqual(x, PublicChannels):
			return ":'pub'", nil
		case reflect.DeepEqual(x, []string{hotMine}):
			return ":'mine'", nil
		case reflect.DeepEqual(x, hiddenChannels):
			return "'{" + strings.Join(x, ",") + "}'", nil
		case len(x) == 0:
			return "'{}'", nil
		}
	case []time.Time:
		if len(x) == 0 {
			return "'{}'", nil
		}
	}
	return "", fmt.Errorf("no psql expression for argument %#v", v)
}

// hotStmtText is the whole copy, as the builders print it today.
func hotStmtText() (string, error) {
	var b strings.Builder
	b.WriteString("-- GENERATED by csi-spl-api internal/store/stmt_print_test.go (TestHotStmtPrint); do not edit.\n")
	fmt.Fprintf(&b, "-- @@pub {%s}\n", strings.Join(PublicChannels, ","))
	for _, s := range hotStmts() {
		exec := make([]string, len(s.args))
		for i, a := range s.args {
			e, err := hotArg(a)
			if err != nil {
				return "", fmt.Errorf("%s $%d: %w", s.name, i+1, err)
			}
			exec[i] = e
		}
		scope := "tenant"
		if s.scope == pgScopeTenantNoJIT {
			scope = "walk"
		}
		if strings.Contains(s.sql, "\n-- @@") || strings.HasPrefix(s.sql, "-- @@") {
			return "", fmt.Errorf("%s: the body holds a header line", s.name)
		}
		sum := sha256.Sum256([]byte(s.sql))
		fmt.Fprintf(&b, "-- @@stmt %s sha256=%s scope=%s exec=%s\n-- @@scope %s\n%s\n",
			s.name, hex.EncodeToString(sum[:]), scope, strings.Join(exec, ","), strings.Join(strings.Fields(s.scope), " "), s.sql)
	}
	return b.String(), nil
}

// TestHotStmtPrint writes the copy; skipped unless SPL_STMT_PRINT names it.
func TestHotStmtPrint(t *testing.T) {
	path := os.Getenv("SPL_STMT_PRINT")
	if path == "" {
		t.Skip("set SPL_STMT_PRINT=<file> to print the hot statements")
	}
	text, err := hotStmtText()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(text), 0o644); err != nil {
		t.Fatal(err)
	}
}

// TestHotStmtCopyCurrent is the drift gate: the action's copy is what the
// builders print now.
func TestHotStmtCopyCurrent(t *testing.T) {
	have, err := os.ReadFile(filepath.FromSlash(hotStmtCopy))
	if os.IsNotExist(err) {
		t.Skip("no csi-spl-orc beside this module")
	}
	if err != nil {
		t.Fatal(err)
	}
	want, err := hotStmtText()
	if err != nil {
		t.Fatal(err)
	}
	if string(have) != want {
		t.Fatalf("%s is stale: a hot statement's builder changed. Regenerate it:\n"+
			"  SPL_STMT_PRINT=$(realpath %s) go test -run '^TestHotStmtPrint$' ./internal/store/", hotStmtCopy, hotStmtCopy)
	}
}
