package repodocs

import (
	"encoding/base64"
	"fmt"
	"os"
	"regexp"
	"strings"
	"testing"
)

// The workflow whose distribution-hygiene Sweep do_check_dist_hygiene runs,
// relative to this package.
const sweepWorkflow = "../../../../../../.github/workflows/10_ci-quality.yml"

// sweepLineRe is sync-hygiene.sh's sed expression: sweep "<label>" '<pattern>'.
var sweepLineRe = regexp.MustCompile(`(?m)^[ \t]*sweep[ \t]+"([^"]+)"[ \t]+'([^']+)'`)

// renderPatterns is what sync-hygiene.sh writes for a workflow's text.
func renderPatterns(workflow string) (string, error) {
	var b strings.Builder
	b.WriteString("# GENERATED by sync-hygiene.sh from the distribution-hygiene Sweep of\n")
	b.WriteString("# .github/workflows/10_ci-quality.yml. Do not edit: run the script.\n")
	b.WriteString("# <label> TAB <base64 of the grep -P pattern>\n")
	m := sweepLineRe.FindAllStringSubmatch(workflow, -1)
	if len(m) == 0 {
		return "", fmt.Errorf("no sweep line")
	}
	for _, s := range m {
		fmt.Fprintf(&b, "%s\t%s\n", s[1], base64.StdEncoding.EncodeToString([]byte(s[2])))
	}
	return b.String(), nil
}

// TestHygienePatternsInSync is the drift test: the embedded copy must be what
// the sync script writes for the workflow on this tree.
func TestHygienePatternsInSync(t *testing.T) {
	wf, err := os.ReadFile(sweepWorkflow)
	if os.IsNotExist(err) {
		t.Skip("no .github/workflows in this checkout (a csi-spl-api-only build context)")
	}
	if err != nil {
		t.Fatal(err)
	}
	want, err := renderPatterns(string(wf))
	if err != nil {
		t.Fatal(err)
	}
	if want != hygienePatterns {
		t.Fatalf("internal/repodocs/hygiene-patterns.tsv is stale against %s - run: bash csi-spl-api/src/go/spool-hub-api/internal/repodocs/sync-hygiene.sh", sweepWorkflow)
	}

	// CONTROLS: the comparison cannot pass vacuously.
	added := strings.Replace(string(wf), "\n          sweep ", "\n          sweep \"planted\" 'x'\n          sweep ", 1)
	if got, _ := renderPatterns(added); got == hygienePatterns {
		t.Error("CONTROL a sweep line added to the workflow did not read as drift")
	}
	edited := strings.Replace(string(wf), `\.op\.fi`, `\.op\.fi|planted`, 1)
	if edited == string(wf) {
		t.Fatal("CONTROL could not plant an edit: the first sweep pattern changed shape")
	}
	if got, _ := renderPatterns(edited); got == hygienePatterns {
		t.Error("CONTROL an edited sweep pattern did not read as drift")
	}
	if _, err := renderPatterns("jobs: {}\n"); err == nil {
		t.Error("CONTROL a workflow with no sweep line was accepted")
	}
}
