#!/usr/bin/env bash
#------------------------------------------------------------------------------
# @description Copy the distribution-hygiene sweep's patterns (the `sweep
# @description "<label>" '<pattern>'` lines of the Sweep step in
# @description .github/workflows/10_ci-quality.yml, the list
# @description do_check_dist_hygiene runs) into hygiene-patterns.tsv, which the
# @description hub embeds (spec 075 repo-edit §5.1), so the hub image needs no
# @description other tree. Each pattern is base64: a plain copy would be a hit
# @description of the very sweep it copies. TestHygienePatternsInSync fails
# @description while the copy differs; this script is how it is refreshed.
# @param --check (optional) - write nothing; exit 1 when the copy is stale
# @example bash csi-spl-api/src/go/spool-hub-api/internal/repodocs/sync-hygiene.sh
#------------------------------------------------------------------------------
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
wf="${HYGIENE_WORKFLOW:-$here/../../../../../../.github/workflows/10_ci-quality.yml}"
out="$here/hygiene-patterns.tsv"

[[ -f "$wf" ]] || { echo "FATAL no workflow at $wf" >&2; exit 1; }

render() {
  local label pattern n=0
  echo "# GENERATED by sync-hygiene.sh from the distribution-hygiene Sweep of"
  echo "# .github/workflows/10_ci-quality.yml. Do not edit: run the script."
  echo "# <label> TAB <base64 of the grep -P pattern>"
  while IFS=$'\t' read -r label pattern; do
    printf '%s\t%s\n' "$label" "$(printf '%s' "$pattern" | base64 -w0)"
    n=$((n + 1))
  done < <(sed -nE "s/^[[:space:]]*sweep[[:space:]]+\"([^\"]+)\"[[:space:]]+'([^']+)'.*/\1\t\2/p" "$wf")
  # No pattern found is a REFUSAL: an empty list would gate nothing.
  (( n > 0 )) || { echo "FATAL no sweep \"<label>\" '<pattern>' line in $wf" >&2; return 1; }
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
render >"$tmp"

if [[ "${1:-}" == --check ]]; then
  if ! cmp -s "$tmp" "$out"; then
    echo "STALE $out - run: bash $here/sync-hygiene.sh" >&2
    exit 1
  fi
  echo "ok - $out matches $wf"
  exit 0
fi
cat "$tmp" >"$out"
echo "wrote $out"
