-- 0166_cost_lines.sql - cost tracking storage (spec 123 v1.0 721839020,
-- sections 4.1, 4.4, 5.1; build lane 1). Forward-only. Owner HUM-10, t1
-- af4bbf51.
--
--   cost_lines     every cost line, one table for every source: GCP billing
--                  export, metered usage, fleet transcripts, agent hours,
--                  invoices, hand entry and estimates. The month table and
--                  the pie are one GROUP BY over it.
--   cost_coverage  one row per (day, source): ok | missing | partial with the
--                  reason. A source that failed a day is visible, never
--                  summed as 0 (the spec 121 unmetered rule).
--
-- The workspace is the tenant (0157, 0165): the spec's workspace_id is the
-- column tenant_id here, so the catalogue gate (rls_failclosed_test.go) and
-- the cross-tenant suite see the table. tenant_id NULL is an ESTATE row
-- (GCP, fleet, boxes): only the operator scope reads or writes it.
--
-- The natural key (section 4.1) is a UNIQUE index NULLS NOT DISTINCT (PG 15+;
-- dev and prd run POSTGRES_16), so an estate row, a row with no agent and a
-- row with no model still collide on a re-read, and the readers UPSERT with
--   ON CONFLICT (day, source, project_or_vendor, tenant_id, agent_id, model, kind)
--   WHERE superseded_by IS NULL DO UPDATE ...
-- The index is partial on the live rows because a hand edit (section 4.4) is
-- a new row that supersedes the old one, never an in-place change: in one
-- transaction take the new id (nextval of the identity), set the old row's
-- superseded_by to it, then insert the new row with that id. superseded_by is
-- a deferred FK for exactly that order.
--
-- RLS in the 0014/0021 shape with the empty-setting guard (NULLIF, CLE-3416):
-- a workspace reads and writes its own rows, the operator every row.
-- costs.read (the 0021 pattern) is asked by the hub at the entry point, like
-- every permission (internal/rbac): biz_owner and admin, not billing.manage
-- (section 5.1, Q-1 = A). The estate view needs costs.read in the operator
-- workspace and runs in the operator scope (operatorAuth). cost_coverage
-- holds no workspace data: any workspace scope may read it (the page's
-- "n of N days complete"), only the operator writes it.
--
-- The rows MUST equal internal/rbac Defaults + Permissions (store
-- TestRBACSeedMatchesDefaults). Runs under the operator RLS scope (spool
-- migrate, rdb 0014). The running image reads none of this, so the file
-- applies before the image that does. DEPLOY ORDER: wf 20 applies it.

CREATE TABLE cost_lines (
    id                bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day               date        NOT NULL,
    source            text        NOT NULL CHECK (source ~ '^[a-z][a-z0-9_.-]{0,63}$'),
    project_or_vendor text        NOT NULL CHECK (length(project_or_vendor) BETWEEN 1 AND 200),
    tenant_id         text        NULL REFERENCES tenants (tenant_id) ON DELETE CASCADE,
    agent_id          text        NULL CHECK (length(agent_id) BETWEEN 1 AND 100),
    model             text        NULL CHECK (length(model) BETWEEN 1 AND 200),
    kind              text        NOT NULL CHECK (kind ~ '^[a-z][a-z0-9_.-]{0,63}$'),
    units             numeric     NOT NULL DEFAULT 0,
    amount_micros     bigint      NOT NULL,
    currency          text        NOT NULL CHECK (currency ~ '^[A-Z]{3}$'),
    usd_micros        bigint      NOT NULL,
    eur_micros        bigint      NOT NULL,
    fx_rate_day       date        NOT NULL,
    list_value_micros bigint      NULL,
    origin            text        NOT NULL CHECK (origin IN
                          ('billing_export', 'metered', 'transcript', 'agent_run', 'invoice', 'hand', 'estimate')),
    run_id            text        NOT NULL CHECK (length(run_id) BETWEEN 1 AND 200),
    read_at           timestamptz NOT NULL DEFAULT now(),
    superseded_by     bigint      NULL REFERENCES cost_lines (id) DEFERRABLE INITIALLY DEFERRED,
    CHECK (superseded_by IS DISTINCT FROM id)
);
CREATE UNIQUE INDEX cost_lines_key ON cost_lines
    (day, source, project_or_vendor, tenant_id, agent_id, model, kind) NULLS NOT DISTINCT
    WHERE superseded_by IS NULL;
CREATE INDEX cost_lines_tenant_day ON cost_lines (tenant_id, day);
CREATE INDEX cost_lines_superseded_by ON cost_lines (superseded_by) WHERE superseded_by IS NOT NULL;

CREATE TABLE cost_coverage (
    day     date        NOT NULL,
    source  text        NOT NULL CHECK (source ~ '^[a-z][a-z0-9_.-]{0,63}$'),
    state   text        NOT NULL CHECK (state IN ('ok', 'missing', 'partial')),
    reason  text        NULL CHECK (length(reason) <= 500),
    run_id  text        NOT NULL CHECK (length(run_id) BETWEEN 1 AND 200),
    read_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (day, source),
    CHECK (state = 'ok' OR coalesce(length(btrim(reason)), 0) > 0)
);

ALTER TABLE cost_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE cost_lines FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_scope ON cost_lines
    USING (tenant_id = NULLIF(current_setting('app.tenant_id', true), ''))
    WITH CHECK (tenant_id = NULLIF(current_setting('app.tenant_id', true), ''));
CREATE POLICY operator_scope ON cost_lines
    USING (current_setting('app.rls_scope', true) = 'operator')
    WITH CHECK (current_setting('app.rls_scope', true) = 'operator');

ALTER TABLE cost_coverage ENABLE ROW LEVEL SECURITY;
ALTER TABLE cost_coverage FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_read ON cost_coverage FOR SELECT
    USING (NULLIF(current_setting('app.tenant_id', true), '') IS NOT NULL);
CREATE POLICY operator_scope ON cost_coverage
    USING (current_setting('app.rls_scope', true) = 'operator')
    WITH CHECK (current_setting('app.rls_scope', true) = 'operator');

INSERT INTO rbac_permissions (permission_id, description) VALUES
    ('costs.read', 'see the cost lines and coverage of the workspace (the estate in the operator workspace)');

INSERT INTO rbac_role_permissions (role_id, permission_id) VALUES
    ('biz_owner', 'costs.read'), ('admin', 'costs.read');
