# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "prd"
gcp_project = "csi-spl-prd"
gcp_region  = "europe-north1"

gcp_services = ["storage.googleapis.com", "iam.googleapis.com", "orgpolicy.googleapis.com"]
