# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org          = "csi"
app          = "spl"
env          = "prd"
STEP         = "005-gcp-domain-verification"
gcp_project  = "csi-spl-prd"
gcp_region   = "europe-north1"
gcp_zone     = "europe-north1-a"
gcp_sa_email = "csi-spl-prd@csi-spl-prd.iam.gserviceaccount.com"

prd_zone_name = "spool-hub"
parent_zone_project = "csi-spl-prd"
verification_records = []
tld_domain = "spool-hub.ai"
