# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "prd"
gcp_project = "csi-spl-prd"
gcp_region  = "europe-north1"

github_repository = "csitea/csi-spl"
pool_id = "github-actions"
provider_id = "github"
deploy_sa_account_id = "csi-spl-deploy-prd"
artifact_repository_id    = "csi-spl-prd-hub"
hub_service_name          = "csi-spl-hub-prd"
hub_runtime_sa_account_id = "csi-spl-hub-prd"
