# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "prd"
gcp_project = "csi-spl-prd"
gcp_region  = "europe-north1"
fqdn        = "spool-hub.ai"
site_id = "csi-spl-prd-site"
cert_preference = "GROUPED"
wait_dns_verification = false
additional_fqdns = ["leiden.spool-hub.ai", "csi-rel.spool-hub.ai", "csitea.spool-hub.ai", "luka.spool-hub.ai", "ora-cam.spool-hub.ai", "pas-psf.spool-hub.ai", "spool.spool-hub.ai", "e2e.spool-hub.ai", "bnc-cpt.spool-hub.ai", "niba-consult.spool-hub.ai", "aleko-gik.spool-hub.ai"]
redirect_fqdns = ["www.spool-hub.ai"]
bind_custom_domain = true
