# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "prd"
gcp_project = "csi-spl-prd"
gcp_region  = "europe-north1"
fqdn        = "spool-hub.ai"
site_id = "csi-spl-prd-site"
cert_preference = "GROUPED"
wait_dns_verification = false
additional_fqdns = ["leiden.spool-hub.ai"]
bind_custom_domain = true
