# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "prd"
gcp_project = "csi-spl-prd"
gcp_region  = "europe-north1"

relay_bucket_name = "csi-spl-883adab5-prd"
object_max_age_days = 1
uniform_bucket_level_access = true
relay_sa_account_id = "csi-spl-rel-prd"
