# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "prd"
gcp_project = "csi-spl-prd"
gcp_region  = "europe-north1"

zone_name = "spool-hub"
zone_description = "spool hub public zone: adopted by 025-gcp-dns-zone, never recreate (registrar NS)"
parent_zone_name = ""
parent_zone_project = ""
cloud_run_mapping_records = [{"name": "api", "rrdatas": ["216.239.32.21", "216.239.34.21", "216.239.36.21", "216.239.38.21"], "type": "A"}, {"name": "api", "rrdatas": ["2001:4860:4802:32::15", "2001:4860:4802:34::15", "2001:4860:4802:36::15", "2001:4860:4802:38::15"], "type": "AAAA"}, {"name": "dev.api", "rrdatas": ["ghs.googlehosted.com."], "type": "CNAME"}, {"name": "leiden", "rrdatas": ["199.36.158.100"], "type": "A"}, {"name": "leiden", "rrdatas": ["\"hosting-site=csi-spl-prd-site\""], "type": "TXT"}, {"name": "csi-rel", "rrdatas": ["199.36.158.100"], "type": "A"}, {"name": "csi-rel", "rrdatas": ["\"hosting-site=csi-spl-prd-site\""], "type": "TXT"}, {"name": "csitea", "rrdatas": ["199.36.158.100"], "type": "A"}, {"name": "csitea", "rrdatas": ["\"hosting-site=csi-spl-prd-site\""], "type": "TXT"}, {"name": "luka", "rrdatas": ["199.36.158.100"], "type": "A"}, {"name": "luka", "rrdatas": ["\"hosting-site=csi-spl-prd-site\""], "type": "TXT"}, {"name": "ora-cam", "rrdatas": ["199.36.158.100"], "type": "A"}, {"name": "ora-cam", "rrdatas": ["\"hosting-site=csi-spl-prd-site\""], "type": "TXT"}, {"name": "pas-psf", "rrdatas": ["199.36.158.100"], "type": "A"}, {"name": "pas-psf", "rrdatas": ["\"hosting-site=csi-spl-prd-site\""], "type": "TXT"}, {"name": "spool", "rrdatas": ["199.36.158.100"], "type": "A"}, {"name": "spool", "rrdatas": ["\"hosting-site=csi-spl-prd-site\""], "type": "TXT"}, {"name": "e2e", "rrdatas": ["199.36.158.100"], "type": "A"}, {"name": "e2e", "rrdatas": ["\"hosting-site=csi-spl-prd-site\""], "type": "TXT"}, {"name": "bnc-cpt", "rrdatas": ["199.36.158.100"], "type": "A"}, {"name": "bnc-cpt", "rrdatas": ["\"hosting-site=csi-spl-prd-site\""], "type": "TXT"}, {"name": "www", "rrdatas": ["199.36.158.100"], "type": "A"}, {"name": "www", "rrdatas": ["\"hosting-site=csi-spl-prd-site\""], "type": "TXT"}]
fqdn = "spool-hub.ai"
