# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "prd"
gcp_project = "csi-spl-prd"
gcp_region  = "europe-north1"

zone_name = "spool-hub"
zone_description = "spool hub public zone: adopted by 025-gcp-dns-zone, never recreate (registrar NS)"
parent_zone_name = ""
parent_zone_project = ""
cloud_run_mapping_records = [{"name": "dev.api", "rrdatas": ["ghs.googlehosted.com."], "type": "CNAME"}]
fqdn = "spool-hub.ai"
