# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "prd"
gcp_project = "csi-spl-prd"
gcp_region  = "europe-north1"

allowed_ip_ranges = ["0.0.0.0/0"]
wui_origin_host = ""
l7_narrowing = false
hub_paths = ["/v1/*", "/api/*", "/healthz", "/version"]
hub_path_regex = "^/(v1/|api/v1/|healthz$|version$)"
fqdn_a_record = false
extra_host_labels = ["api"]
dns_managed_zone = "spool-hub"
dns_zone_project = ""
extra_dns_managed_zone = ""
extra_dns_zone_project = ""
service_name = "csi-spl-hub-prd"
fqdn         = "spool-hub.ai"
base_domain  = "spool-hub.ai"
