# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org          = "csi"
app          = "spl"
env          = "prd"
STEP         = "032-gcp-cloud-run-domain-mapping"
gcp_project  = "csi-spl-prd"
gcp_region   = "europe-north1"
gcp_zone     = "europe-north1-a"
gcp_sa_email = "csi-spl-prd@csi-spl-prd.iam.gserviceaccount.com"
# the hub service (030) and the hosts it answers on: the api host
# env.dns.api_fqdn (derived by do_spl_merged_cnf, the same host the OAuth
# callbacks use, so the two cannot drift) and one per env.dns.mapped_tenants entry
# (<tenant>.<fqdn>); names come from cnf, the domain from env.dns only
cloud_run_service_name       = "csi-spl-hub-prd"
cloud_run_custom_domain      = "api.spool-hub.ai"
cloud_run_additional_domains = []
