# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "prd"
gcp_project = "csi-spl-prd"
gcp_region  = "europe-north1"

instance_name = "csi-spl-prd-pg"
database_version = "POSTGRES_16"
tier = "db-f1-micro"
availability_type = "ZONAL"
disk_size_gb = 10
database_name = "spool"
deletion_protection = true
backup_enabled = true
query_insights_enabled = true
query_insights_string_length = 1024
query_insights_plans_per_minute = 5
dsn_secret_id = "csi-spl-hub-db-dsn"
owner_dsn_secret_id = "csi-spl-hub-db-owner-dsn"
