# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "prd"
gcp_project = "csi-spl-prd"
gcp_region  = "europe-north1"

instance_name = "csi-spl-prd-pg"
backups_bucket_name = "csi-spl-prd-db-backups"
backup_max_age_days = 30
soft_delete_retention_seconds = 604800
