# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org        = "csi"
app        = "spl"
env        = "prd"
gcp_region = "europe-north1"

tf_key_project = "csi-spl-bkp"
offsite_bucket_name = "csi-spl-bkp-prd"
writer_service_account = "csi-spl-prd@csi-spl-prd.iam.gserviceaccount.com"
retention_days = 30
max_age_days = 90
noncurrent_max_age_days = 30
soft_delete_retention_seconds = 2592000
