# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "prd"
gcp_project = "csi-spl-prd"
gcp_region  = "europe-north1"
hub_runtime_sa_account_id = "csi-spl-hub-prd"

docs_bucket_name = "csi-spl-prd-docs"
soft_delete_retention_seconds = 604800
