# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "prd"
gcp_project = "csi-spl-prd"
gcp_region  = "europe-north1"
hub_runtime_sa_account_id = "csi-spl-hub-prd"

bucket_prefix = "csi-spl-prd-docs-"
workspaces = ["t1", "leiden", "csi-rel", "csitea", "luka", "ora-cam", "pas-psf", "spool", "e2e", "bnc-cpt", "niba-consult"]
soft_delete_retention_seconds = 604800
