# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
# spec 057: the satellite's step, run as the csi-spl-all SA in csi-spl-all
# (steps.059-gcp-satellite-budget.gcp_project, the 046 pattern). Rendered from prd only: in dev the
# steps block is absent, so this renders the header only and the step's env
# validation refuses a dev plan.

# runtime-vars: billing_account_id
org         = "csi"
app         = "spl"
env         = "prd"
gcp_project = "csi-spl-all"
gcp_region  = "europe-north1"

budget_display_name = "csi-spl-all-satellite"
budget_amount_month = 170
threshold_percents = [0.5, 0.9, 1.0]
budget_label_key = "box"
budget_label_value = "satellite"
