# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
# spec 057: the satellite lives in csi-spl-all, so its state lives in that
# project's own bucket (the 046 pattern). Rendered from prd only.
bucket = "csi-spl-all-tfstate"
prefix = "terraform/059-gcp-satellite-budget"
