# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/prd.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
# spec 057: the satellite's step, run as the csi-spl-all SA in csi-spl-all
# (steps.060-gcp-vm-satellite.gcp_project, the 046 pattern). Rendered from prd only: in dev the
# steps block is absent, so this renders the header only and the step's env
# validation refuses a dev plan.

org         = "csi"
app         = "spl"
env         = "prd"
gcp_project = "csi-spl-all"
gcp_region  = "europe-north1"

vm_name = "csi-spl-all-satellite"
gcp_zone = "europe-north1-a"
subnet_cidr = "10.80.0.0/24"
machine_type = "e2-highmem-4"
boot_disk_image = "projects/debian-cloud/global/images/debian-13-trixie-v20260921"
boot_disk_size_gb = 30
data_disk_name = "csi-spl-all-satellite-data"
data_disk_type = "pd-balanced"
data_disk_size_gb = 100
os_user = "debian"
ssh_public_key_file = "~/.ssh/.csi/debian@csi-spl-all-satellite.pub"
ssh_source_ranges = ["35.235.240.0/20"]
iap_members = []
box_label = "satellite"
