# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/dev.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "dev"
gcp_project = "csi-spl-dev"
gcp_region  = "europe-north1"

gcp_services = ["storage.googleapis.com", "iam.googleapis.com", "orgpolicy.googleapis.com", "run.googleapis.com", "sqladmin.googleapis.com", "secretmanager.googleapis.com", "artifactregistry.googleapis.com", "dns.googleapis.com", "compute.googleapis.com", "certificatemanager.googleapis.com", "iamcredentials.googleapis.com", "sts.googleapis.com", "firebase.googleapis.com", "firebasehosting.googleapis.com"]
