# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/dev.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "dev"
gcp_project = "csi-spl-dev"
gcp_region  = "europe-north1"
deploy_sa_account_id = "csi-spl-dev-fb-deploy"
deploy_roles = ["roles/firebasehosting.admin", "roles/serviceusage.serviceUsageConsumer", "roles/run.viewer"]
bind_github_wif = false
wif_pool_id     = "github-actions"
github_ref      = "refs/heads/master"
