# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/dev.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "dev"
gcp_project = "csi-spl-dev"
gcp_region  = "europe-north1"
fqdn        = "dev.spool-hub.ai"
site_id = "csi-spl-dev-site"
cert_preference = "GROUPED"
wait_dns_verification = false
additional_fqdns = ["csitea.dev.spool-hub.ai", "e2e.dev.spool-hub.ai"]
bind_custom_domain = true
