# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/dev.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "dev"
gcp_project = "csi-spl-dev"
gcp_region  = "europe-north1"

relay_bucket_name = "csi-spl-dev-rel"
object_max_age_days = 0
soft_delete_retention_seconds = 604800
relay_sa_account_id = "csi-spl-rel-dev"
