# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/dev.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "dev"
gcp_project = "csi-spl-dev"
gcp_region  = "europe-north1"

allowed_ip_ranges = ["0.0.0.0/0"]
wui_origin_host = "csi-spl-dev-site.web.app"
l7_narrowing = true
extra_host_labels = ["dev.api"]
dns_managed_zone = "spool-hub"
dns_zone_project = "csi-spl-prd"
service_name = "csi-spl-hub-dev"
fqdn         = "dev.spool-hub.ai"
base_domain  = "spool-hub.ai"
