# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/dev.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "dev"
gcp_project = "csi-spl-dev"
gcp_region  = "europe-north1"

allowed_ip_ranges = []
dns_managed_zone = ""
service_name = "csi-spl-hub-dev"
fqdn         = "dev.spool-hub.ai"
