# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/dev.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org          = "csi"
app          = "spl"
env          = "dev"
STEP         = "032-gcp-cloud-run-domain-mapping"
gcp_project  = "csi-spl-dev"
gcp_region   = "europe-north1"
gcp_zone     = "europe-north1-a"
gcp_sa_email = "csi-spl-dev@csi-spl-dev.iam.gserviceaccount.com"
# the hub service (030) and the hosts it answers on: the api host
# env.dns.api_fqdn (derived by do_spl_merged_cnf, the same host the OAuth
# callbacks use, so the two cannot drift). Tenant hosts <tenant>.<fqdn> are
# the WUI's (019 Firebase custom domains, SPL-959), never a hub mapping.
cloud_run_service_name       = "csi-spl-hub-dev"
cloud_run_custom_domain      = "dev.api.spool-hub.ai"
cloud_run_additional_domains = []
