# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/dev.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
# The state lives in the BACKUP project's own state bucket, not in the env's:
# a destroy of csi-spl-dev must not take the record of this bucket with it.
bucket = "csi-spl-bkp-tfstate"
prefix = "terraform/046-gcs-offsite-backups/dev"
