# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/dev.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "dev"
gcp_project = "csi-spl-dev"
gcp_region  = "europe-north1"

files_bucket_name = "csi-spl-dev-files"
soft_delete_retention_seconds = 604800
object_max_age_days = 0
