# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/dev.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "dev"
gcp_project = "csi-spl-dev"
gcp_region  = "europe-north1"
hub_runtime_sa_account_id = "csi-spl-hub-dev"

docs_bucket_name = "csi-spl-dev-docs"
soft_delete_retention_seconds = 604800
