# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/dev.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "csi"
app         = "spl"
env         = "dev"
gcp_project = "csi-spl-dev"
gcp_region  = "europe-north1"
project_sa_email = "csi-spl-dev@csi-spl-dev.iam.gserviceaccount.com"

state_bucket_name = "csi-spl-dev-box-state"
writer_sa_account_id = "csi-spl-dev-box-state"
retention_days = 30
soft_delete_retention_seconds = 604800
