# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/dev.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
# spec 057: the satellite's step, run as the csi-spl-all SA in csi-spl-all
# (steps.059-gcp-satellite-budget.gcp_project, the 046 pattern). Rendered from prd only: in dev the
# steps block is absent, so this renders the header only and the step's env
# validation refuses a dev plan.

# prd-only-step

# runtime-vars: billing_account_id
org         = "csi"
app         = "spl"
env         = "dev"
gcp_project = "csi-spl-dev"
gcp_region  = "europe-north1"

