# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/dev.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
# availability plan row R03. The owner's address is NOT rendered here: 070
# reads cnf env.gcp.gcp_account_owner_email as TF_VAR_GCP_ACCOUNT_OWNER_EMAIL,
# which do_tf_init exports from the env.gcp section.
# runtime-vars: GCP_ACCOUNT_OWNER_EMAIL
org         = "csi"
app         = "spl"
env         = "dev"
gcp_project = "csi-spl-dev"
gcp_region  = "europe-north1"

health_path = "/v1/health"
health_content = "\"status\":\"ok\""
uptime_regions = ["EUROPE", "USA", "ASIA_PACIFIC"]
uptime_period_seconds = 60
uptime_timeout_seconds = 10
uptime_failing_regions = 1
uptime_fail_seconds = 120
rate_429_per_min = 20
rate_5xx_per_5min = 5
error_logs_per_5min = 10
sql_down_seconds = 120
auto_close_seconds = 1800
hub_service_name        = "csi-spl-hub-dev"
cloud_sql_instance_name = "csi-spl-dev-pg"
uptime_host             = "dev.api.spool-hub.ai"
