# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org          = "{{ ORG }}"
app          = "{{ APP }}"
env          = "{{ ENV }}"
STEP         = "005-gcp-domain-verification"
gcp_project  = "{{ gcp["gcp_project"] }}"
gcp_region   = "{{ gcp["gcp_region"] }}"
gcp_zone     = "{{ gcp["gcp_region"] }}-a"
gcp_sa_email = "{{ ORG }}-{{ APP }}-{{ ENV }}@{{ gcp["gcp_project"] }}.iam.gserviceaccount.com"
{% for key, value in steps["005-gcp-domain-verification"].items() %}
{{ key }} = {{ value | tojson }}
{%- endfor %}
tld_domain = {{ dns["BASE_DOMAIN"] | tojson }}
