# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ gcp["gcp_project"] }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
deploy_sa_account_id = "{{ ORG }}-{{ APP }}-{{ ENV }}-fb-deploy"
deploy_roles = ["roles/firebasehosting.admin", "roles/serviceusage.serviceUsageConsumer", "roles/run.viewer"]
