# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ gcp["gcp_project"] }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
{% for key, value in steps["017-github-wif-deploy"].items() %}
{{ key }} = {{ value | tojson }}
{%- endfor %}
artifact_repository_id    = {{ steps["028-gcp-artifact-registry"]["repository_id"] | tojson }}
hub_service_name          = {{ hub["service_name"] | tojson }}
hub_runtime_sa_account_id = {{ hub["runtime_sa_account_id"] | tojson }}
