# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ gcp["gcp_project"] }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
fqdn        = "{{ dns["fqdn"] }}"
site_id = "{{ ORG }}-{{ APP }}-{{ ENV }}-site"
cert_preference = "GROUPED"
wait_dns_verification = false
{#- SPL-959 (owner option B 2026-09-26): every env.dns.mapped_tenants entry is a
    custom domain <tenant>.<fqdn> of THIS site (the WUI), next to the cnf extras #}
{%- set ns = namespace(extra=(steps["019-firebase-static-site"].get("additional_fqdns") or [])) %}
{%- for t in (dns.get("mapped_tenants") or []) %}
{%- set ns.extra = ns.extra + [t ~ "." ~ dns["fqdn"]] %}
{%- endfor %}
additional_fqdns = {{ ns.extra | tojson }}
{#- owner 2026-09-29 (e802196b): env.dns.redirect_hosts (e.g. www) are custom
    domains that 301-redirect to the fqdn; their A + TXT are 025's #}
{%- set rd = namespace(list=[]) %}
{%- for h in (dns.get("redirect_hosts") or []) %}
{%- set rd.list = rd.list + [h ~ "." ~ dns["fqdn"]] %}
{%- endfor %}
redirect_fqdns = {{ rd.list | tojson }}
bind_custom_domain = {{ steps["019-firebase-static-site"].get("bind_custom_domain", false) | tojson }}
