# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ gcp["gcp_project"] }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
fqdn        = "{{ dns["fqdn"] }}"
site_id = "{{ ORG }}-{{ APP }}-{{ ENV }}-site"
cert_preference = "GROUPED"
wait_dns_verification = false
additional_fqdns = []
bind_custom_domain = {{ steps["019-firebase-static-site"].get("bind_custom_domain", false) | tojson }}
