# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ gcp["gcp_project"] }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
{% for key, value in steps["025-gcp-dns-zone"].items() if key not in ["cloud_run_mapping_records", "mapped_tenant_records"] %}
{{ key }} = {{ value | tojson }}
{%- endfor %}
{%- set ns = namespace(recs=(steps["025-gcp-dns-zone"].get("cloud_run_mapping_records") or [])) %}
{%- for t in ((dns.get("mapped_tenants") or []) if steps["025-gcp-dns-zone"].get("mapped_tenant_records") else []) %}
{#- SPL-959: a tenant host is a Firebase Hosting custom domain of the WUI site
    (019), as the apex: A 199.36.158.100 + TXT hosting-site=<site> #}
{%- set ns.recs = ns.recs + [{"name": t, "type": "A", "rrdatas": ["199.36.158.100"]}, {"name": t, "type": "TXT", "rrdatas": ["\"hosting-site=" ~ ORG ~ "-" ~ APP ~ "-" ~ ENV ~ "-site\""]}] %}
{%- endfor %}
{%- for h in (dns.get("redirect_hosts") or []) %}
{#- owner 2026-09-29 (e802196b): a redirect host (019 redirect_fqdns) is a
    Firebase custom domain too: the same A + TXT hosting-site as a tenant host #}
{%- set ns.recs = ns.recs + [{"name": h, "type": "A", "rrdatas": ["199.36.158.100"]}, {"name": h, "type": "TXT", "rrdatas": ["\"hosting-site=" ~ ORG ~ "-" ~ APP ~ "-" ~ ENV ~ "-site\""]}] %}
{%- endfor %}
cloud_run_mapping_records = {{ ns.recs | tojson }}
fqdn = {{ dns["fqdn"] | tojson }}
