# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ gcp["gcp_project"] }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
{% for key, value in steps["030-cloud-run-hub"].items() %}
{{ key }} = {{ value | tojson }}
{%- endfor %}
image                        = {{ hub["image"]["ref"] | tojson }}
service_name                 = {{ hub["service_name"] | tojson }}
runtime_sa_account_id        = {{ hub["runtime_sa_account_id"] | tojson }}
container_port               = {{ hub["cloud_run"]["port"] | tojson }}
cpu                          = {{ hub["cloud_run"]["cpu"] | tojson }}
memory                       = {{ hub["cloud_run"]["memory"] | tojson }}
min_instances                = {{ hub["cloud_run"]["min_instances"] | tojson }}
max_instances                = {{ hub["cloud_run"]["max_instances"] | tojson }}
concurrency                  = {{ hub["cloud_run"]["concurrency"] | tojson }}
timeout_seconds              = {{ hub["cloud_run"]["timeout_seconds"] | tojson }}
ingress                      = {{ hub["cloud_run"]["ingress"] | tojson }}
cloud_sql_instance_name      = {{ steps["040-cloud-sql-postgres"]["instance_name"] | tojson }}
files_bucket_name            = {{ steps["050-gcs-files"]["files_bucket_name"] | tojson }}
environment_variables        = {{ hub["env"] | tojson }}
secret_environment_variables = {{ hub["secret_env"] | tojson }}
