# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ gcp["gcp_project"] }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
{% for key, value in steps["030-cloud-run-hub"].items() %}
{{ key }} = {{ value | tojson }}
{%- endfor %}
image                        = {{ hub["image"]["ref"] | tojson }}
service_name                 = {{ hub["service_name"] | tojson }}
runtime_sa_account_id        = {{ hub["runtime_sa_account_id"] | tojson }}
container_port               = {{ hub["cloud_run"]["port"] | tojson }}
cpu                          = {{ hub["cloud_run"]["cpu"] | tojson }}
memory                       = {{ hub["cloud_run"]["memory"] | tojson }}
min_instances                = {{ hub["cloud_run"]["min_instances"] | tojson }}
max_instances                = {{ hub["cloud_run"]["max_instances"] | tojson }}
concurrency                  = {{ hub["cloud_run"]["concurrency"] | tojson }}
timeout_seconds              = {{ hub["cloud_run"]["timeout_seconds"] | tojson }}
ingress                      = {{ hub["cloud_run"]["ingress"] | tojson }}
deletion_protection          = {{ hub["cloud_run"]["deletion_protection"] | tojson }}
cloud_sql_instance_name      = {{ steps["040-cloud-sql-postgres"]["instance_name"] | tojson }}
files_bucket_name            = {{ steps["050-gcs-files"]["files_bucket_name"] | tojson }}
{#- spec 010 T020: auth.social.env, auth.native.env and mail.env join hub.env
    (plain values). Secrets are injected only when used, since Cloud Run refuses
    a revision whose secret has no version: the session key when an IdP is
    listed or native sign-in is enabled, each LISTED IdP's client secret, and the
    SMTP password while SPOOL_HUB_MAIL_TRANSPORT=smtp. Every slot is created. #}
{%- set auth_env = auth["social"]["env"] %}
{%- set auth_sec = auth["social"]["secret_env"] %}
{%- set run_env = dict(hub["env"], **auth_env) %}
{%- set run_sec = dict(hub["secret_env"]) %}
{%- set listed = auth_env["SPOOL_HUB_AUTH_PROVIDERS"].split(",") | map("trim") | reject("equalto", "") | list %}
{#- native sign-in (spec 015) needs the session key even with no IdP listed #}
{%- set native_env = auth["native"]["env"] if (auth["native"] is defined and auth["native"]["env"] is defined) else {} %}
{%- set native_on = (native_env.get("SPOOL_HUB_AUTH_NATIVE_ENABLED", "false") | string | lower) == "true" %}
{%- set _ = run_env.update(native_env) %}
{%- if native_on %}
{%- set _ = run_sec.update({"SPOOL_HUB_AUTH_SESSION_KEY": auth_sec["SPOOL_HUB_AUTH_SESSION_KEY"]}) %}
{%- endif %}
{%- set mail_env = mail["env"] if (mail is defined and mail["env"] is defined) else {} %}
{%- set mail_sec = mail["secret_env"] if (mail is defined and mail["secret_env"] is defined) else {} %}
{%- set _ = run_env.update(mail_env) %}
{%- if mail_env.get("SPOOL_HUB_MAIL_TRANSPORT", "none") == "smtp" %}
{%- set _ = run_sec.update(mail_sec) %}
{%- endif %}
{#- spec 014 T020: the box-wui key slot always exists; SPOOL_HUB_WUI_KEY is
    injected only while hub.wui_key.inject is "true" (a version exists) #}
{%- set wui_key = hub["wui_key"] if hub["wui_key"] is defined else {} %}
{%- set wui_sec = wui_key["secret_env"] if wui_key["secret_env"] is defined else {} %}
{%- if (wui_key.get("inject", "false") | string | lower) == "true" %}
{%- set _ = run_sec.update(wui_sec) %}
{%- endif %}
{#- spec 065 L4: the release-note bans slot always exists; injected only
    while hub.release_note_bans.inject is "true" (a version exists) #}
{%- set rnb = hub["release_note_bans"] if hub["release_note_bans"] is defined else {} %}
{%- set rnb_sec = rnb["secret_env"] if rnb["secret_env"] is defined else {} %}
{%- if (rnb.get("inject", "false") | string | lower) == "true" %}
{%- set _ = run_sec.update(rnb_sec) %}
{%- endif %}
{#- 006 T022: the stripe pair only while the provider is stripe, the PayPal
    secret only while SPOOL_HUB_ENABLE_PAYPAL is "true"; every slot exists #}
{%- set pay_sec = payment["secret_env"] if (payment is defined and payment["secret_env"] is defined) else {} %}
{%- if hub["env"].get("SPOOL_HUB_PAYMENT_PROVIDER", "") == "stripe" %}
{%- for k in ["SPOOL_HUB_STRIPE_SECRET_KEY", "SPOOL_HUB_STRIPE_WEBHOOK_SECRET"] %}
{%- set _ = run_sec.update({k: pay_sec[k]}) %}
{%- endfor %}
{%- endif %}
{%- if (hub["env"].get("SPOOL_HUB_ENABLE_PAYPAL", "false") | string | lower) == "true" %}
{%- set _ = run_sec.update({"SPOOL_HUB_PAYPAL_CLIENT_SECRET": pay_sec["SPOOL_HUB_PAYPAL_CLIENT_SECRET"]}) %}
{%- endif %}
{#- spec 090 T002: the two LinkedIn marketing app slots always exist; injected
    only while marketing.linkedin.inject is "true" (both versions exist) #}
{%- set mkt_li = marketing["linkedin"] if (marketing is defined and marketing["linkedin"] is defined) else {} %}
{%- set mkt_sec = {"SPOOL_HUB_MARKETING_LINKEDIN_CLIENT_ID": mkt_li["client_id_secret"], "SPOOL_HUB_MARKETING_LINKEDIN_CLIENT_SECRET": mkt_li["client_secret_secret"]} if mkt_li else {} %}
{%- if (mkt_li.get("inject", "false") | string | lower) == "true" %}
{%- set _ = run_sec.update(mkt_sec) %}
{%- endif %}
{#- spec 090 switch: the outer allow-list reaches the hub as one plain env
    value, the workspace ids joined with commas, or the literal "all" #}
{%- set mkt_ws = marketing["workspaces"] if (marketing is defined and marketing["workspaces"] is defined) else [] %}
{%- set _ = run_env.update({"SPOOL_HUB_MARKETING_WORKSPACES": (mkt_ws if mkt_ws is string else (mkt_ws | join(",")))}) %}
{#- spec 075 repo-edit T01: the GitHub App key's slot is 07's own resource
    (imported, never in auth_secret_ids); SPOOL_GITHUB_APP_KEY is injected
    only while docs.repo_edit.inject is "true" (a version exists) #}
{%- set gh_app = docs["repo_edit"] if (docs is defined and docs["repo_edit"] is defined) else {} %}
{%- set gh_sec = gh_app["secret_env"] if gh_app["secret_env"] is defined else {} %}
{%- if (gh_app.get("inject", "false") | string | lower) == "true" %}
{%- set _ = run_sec.update(gh_sec) %}
{%- endif %}
{%- set slot_ids =(auth_sec.values() | list) + (mail_sec.values() | list) + (wui_sec.values() | list) + (pay_sec.values() | list) + (rnb_sec.values() | list) + (mkt_sec.values() | list) %}
{%- if listed %}
{%- set _ = run_sec.update({"SPOOL_HUB_AUTH_SESSION_KEY": auth_sec["SPOOL_HUB_AUTH_SESSION_KEY"]}) %}
{%- for p in listed %}
{%- set k = "SPOOL_HUB_AUTH_" ~ (p | upper) ~ "_CLIENT_SECRET" %}
{%- set _ = run_sec.update({k: auth_sec[k]}) %}
{%- endfor %}
{%- endif %}
environment_variables        = {{ run_env | tojson }}
secret_environment_variables = {{ run_sec | tojson }}
auth_secret_ids              = {{ slot_ids | tojson }}
github_app_key_secret_id     = {{ gh_sec["SPOOL_GITHUB_APP_KEY"] | tojson }}
