# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ gcp["gcp_project"] }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
{% for key, value in steps["031-gcp-hub-ingress"].items() %}
{{ key }} = {{ value | tojson }}
{%- endfor %}
service_name = {{ hub["service_name"] | tojson }}
fqdn         = {{ dns["fqdn"] | tojson }}
base_domain  = {{ dns["BASE_DOMAIN"] | tojson }}
