# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
# runtime-vars: proj_path
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ gcp["gcp_project"] }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
{% for key, value in steps["036-spl-demo-workspace"].items() %}
{{ key }} = {{ value | tojson }}
{%- endfor %}
