# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ gcp["gcp_project"] }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
{% for key, value in steps["040-cloud-sql-postgres"].items() %}
{{ key }} = {{ value | tojson }}
{%- endfor %}
dsn_secret_id = {{ hub["secret_env"]["SPOOL_HUB_DB_DSN"] | tojson }}
owner_dsn_secret_id = {{ hub["db_owner_dsn_secret"] | tojson }}
