# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
# The state lives in the BACKUP project's own state bucket, not in the env's:
# a destroy of csi-spl-{{ ENV }} must not take the record of this bucket with it.
bucket = "{{ steps["046-gcs-offsite-backups"]["tf_state_bucket"] }}"
prefix = "terraform/046-gcs-offsite-backups/{{ ENV }}"
