# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org        = "{{ ORG }}"
app        = "{{ APP }}"
env        = "{{ ENV }}"
gcp_region = "{{ gcp["gcp_region"] }}"
{% for key, value in steps["046-gcs-offsite-backups"].items() if key not in ("tf_state_bucket", "copy_enabled") %}
{{ key }} = {{ value | tojson }}
{%- endfor %}
