# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ gcp["gcp_project"] }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
hub_runtime_sa_account_id = {{ hub["runtime_sa_account_id"] | tojson }}
{% for key, value in steps["052-gcs-workspace-docs"].items() %}
{{ key }} = {{ value | tojson }}
{%- endfor %}
