# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ gcp["gcp_project"] }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
deploy_sa_account_id = {{ steps["016-firebase-deploy-iam"]["deploy_sa_account_id"] | tojson }}
{% for key, value in steps["054-gcs-blog-media"].items() %}
{{ key }} = {{ value | tojson }}
{%- endfor %}
