# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ gcp["gcp_project"] }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
hub_runtime_sa_account_id = {{ hub["runtime_sa_account_id"] | tojson }}
kms_check_sa_account_id   = "{{ ORG }}-{{ APP }}-{{ ENV }}"

key_ring        = {{ marketing["kms_key"]["key_ring"] | tojson }}
crypto_key      = {{ marketing["kms_key"]["crypto_key"] | tojson }}
rotation_period = {{ marketing["kms_key"]["rotation_period"] | tojson }}
