# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ gcp["gcp_project"] }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
project_sa_email = "{{ gcp["gcp_project"] }}@{{ gcp["gcp_project"] }}.iam.gserviceaccount.com"
{% for key, value in steps["056-gcs-box-state"].items() %}
{{ key }} = {{ value | tojson }}
{%- endfor %}
