# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
# spec 057: the satellite's step, run as the csi-spl-all SA in csi-spl-all
# (steps.059-gcp-satellite-budget.gcp_project, the 046 pattern). Rendered from prd only: in dev the
# steps block is absent, so this renders the header only and the step's env
# validation refuses a dev plan.
{% if ENV != "prd" %}
# prd-only-step
{% endif %}
# runtime-vars: billing_account_id
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ steps.get("059-gcp-satellite-budget", {}).get("gcp_project", gcp["gcp_project"]) }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
{% for key, value in steps.get("059-gcp-satellite-budget", {}).items() if key not in ("tf_key_project", "tf_state_bucket", "gcp_project") %}
{{ key }} = {{ value | tojson }}
{%- endfor %}
