# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
# spec 057: the satellite lives in csi-spl-all, so its state lives in that
# project's own bucket (the 046 pattern). Rendered from prd only.
bucket = "{{ steps.get("060-gcp-vm-satellite", {}).get("tf_state_bucket", "") }}"
prefix = "terraform/060-gcp-vm-satellite"
