# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
# spec 057: the satellite's step, run as the csi-spl-all SA in csi-spl-all
# (steps.060-gcp-vm-satellite.gcp_project, the 046 pattern). Rendered from prd only: in dev the
# steps block is absent, so this renders the header only and the step's env
# validation refuses a dev plan.
{% if ENV != "prd" %}
# prd-only-step
{% endif %}
# runtime-vars: proj_path
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ steps.get("060-gcp-vm-satellite", {}).get("gcp_project", gcp["gcp_project"]) }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
{# box_owner_user / box_agent_user are the playbook's (role 05 reads <env>.env.json), not terraform's #}{% for key, value in steps.get("060-gcp-vm-satellite", {}).items() if key not in ("tf_key_project", "tf_state_bucket", "gcp_project", "box_owner_user", "box_agent_user") %}
{{ key }} = {{ value | tojson }}
{%- endfor %}
