# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
# availability plan row R03. The alert recipients are NOT rendered here: 070
# reads cnf env.gcp.alert_email_<n> / alert_sms_<n> as TF_VAR_ALERT_EMAIL_<n>
# / TF_VAR_ALERT_SMS_<n>, which do_tf_init exports from the env.gcp section.
# runtime-vars: ALERT_EMAIL_1,ALERT_EMAIL_2,ALERT_EMAIL_3,ALERT_SMS_1,ALERT_SMS_2
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ gcp["gcp_project"] }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
{% for key, value in steps["070-gcp-monitoring"].items() %}
{{ key }} = {{ value | tojson }}
{%- endfor %}
hub_service_name        = {{ hub["service_name"] | tojson }}
cloud_sql_instance_name = {{ steps["040-cloud-sql-postgres"]["instance_name"] | tojson }}
uptime_host             = {{ (dns.get("api_fqdn") or "") | tojson }}
