# GENERATED by tpl-gen from csi-spl-cnf/csi-spl/{{ ENV }}.env.yaml. Do not edit; edit the yaml and re-run do_tpl_gen.
# availability plan row R03. The owner's address is NOT rendered here: 070
# reads cnf env.gcp.gcp_account_owner_email as TF_VAR_GCP_ACCOUNT_OWNER_EMAIL,
# which do_tf_init exports from the env.gcp section.
# runtime-vars: GCP_ACCOUNT_OWNER_EMAIL
org         = "{{ ORG }}"
app         = "{{ APP }}"
env         = "{{ ENV }}"
gcp_project = "{{ gcp["gcp_project"] }}"
gcp_region  = "{{ gcp["gcp_region"] }}"
{% for key, value in steps["070-gcp-monitoring"].items() %}
{{ key }} = {{ value | tojson }}
{%- endfor %}
hub_service_name        = {{ hub["service_name"] | tojson }}
cloud_sql_instance_name = {{ steps["040-cloud-sql-postgres"]["instance_name"] | tojson }}
uptime_host             = {{ (dns.get("api_fqdn") or "") | tojson }}
