# The satellite's in-VM setup is Ansible, the eli-vta pattern
# (eli-vta-inf 130-org-app-gcp-vm/06.app-vm-ansible.tf; owner, topic 6f10f92b:
# "you MUST use the established ansible approach ... not do anything ad-hoc").
# Terraform writes two files from what it just built, and do_tf_apply runs the
# second one right after the apply, inside the tf-runner container:
#   inventory.<env>.ini                         the host, reached over IAP
#   src/bash/scripts/run-ansible-<org>-<app>-<env>-<step>.sh
#                                               syntax-check, then box-playbook.yaml
# The one adaptation: eli-vta's VM has a public IP, the satellite has none, so
# the inventory carries satellite-iap-proxy.sh as the ssh ProxyCommand (the
# csi-spl-all SA key from ~/.gcp, mounted into the container, never baked in).
# Neither file holds a secret: the playbook reads the SA keys and the GitHub
# token on the controller at run time, under no_log. Both are git-ignored.
#
# Ad hoc, the same script straight in the container (the eli-vta comment):
#   docker exec -it con-csi-csi-spl-tf-runner bash <proj_path>/src/bash/scripts/run-ansible-csi-spl-prd-060-gcp-vm-satellite.sh
# or, from the host, the named action: ./run -a do_satellite_playbook

variable "proj_path" {
  type        = string
  description = "csi-spl-iac's path in the tf-runner (TF_VAR_proj_path, exported by do_tf_init). Empty: no ansible files are written (a bare plan)."
  default     = ""
}

locals {
  ansible_step      = "060-gcp-vm-satellite"
  ansible_dir       = "${var.proj_path}/src/terraform/${local.ansible_step}"
  ansible_inventory = "${local.ansible_dir}/inventory.${var.env}.ini"
  ansible_script    = "${var.proj_path}/src/bash/scripts/run-ansible-${var.org}-${var.app}-${var.env}-${local.ansible_step}.sh"
  ansible_log       = "${var.proj_path}/dat/log/ansible.${local.ansible_step}.${var.org}-${var.app}-${var.env}.log"
  ssh_private_key   = trimsuffix(pathexpand(var.ssh_public_key_file), ".pub")
  iap_proxy         = "${var.proj_path}/src/bash/scripts/satellite-iap-proxy.sh"
  ansible_files     = var.proj_path == "" ? 0 : 1
}

resource "local_file" "ansible_inventory" {
  count           = local.ansible_files
  filename        = local.ansible_inventory
  file_permission = "0644"
  content         = <<-EOT
    # GENERATED by terraform ${local.ansible_step} (07-ansible.tf); do not edit, re-apply.
    [satellite]
    ${google_compute_instance.satellite.name} ansible_user=${var.os_user} ansible_ssh_private_key_file=${local.ssh_private_key} ansible_python_interpreter=/usr/bin/python3

    [satellite:vars]
    ansible_ssh_common_args='-o ProxyCommand="bash ${local.iap_proxy} ${var.gcp_project} ${var.gcp_zone} %h %p" -o IdentitiesOnly=yes -o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=~/.ssh/known_hosts.satellite -o ServerAliveInterval=30 -o ConnectTimeout=60'

    [local]
    localhost ansible_connection=local
  EOT
}

resource "local_file" "ansible_script" {
  count           = local.ansible_files
  filename        = local.ansible_script
  file_permission = "0755"
  content         = <<-EOT
    #!/bin/bash
    # GENERATED by terraform ${local.ansible_step} (07-ansible.tf); do not edit, re-apply.
    # Runs the satellite's box-playbook.yaml, in the tf-runner container:
    #   docker exec -it con-${var.org}-${var.org}-${var.app}-tf-runner bash ${local.ansible_script}
    # Extra args pass through to ansible-playbook (e.g. --check --diff, --tags 05_users).
    set -uo pipefail
    export ANSIBLE_FORCE_COLOR=true PYTHONUNBUFFERED=1
    export ANSIBLE_ROLES_PATH=${local.ansible_dir}/roles
    mkdir -p "$(dirname ${local.ansible_log})"

    ansible-playbook --syntax-check -i ${local.ansible_inventory} ${local.ansible_dir}/box-playbook.yaml \
      || { echo "Syntax check failed, exiting..."; exit 1; }

    timeout 60m ansible-playbook ${local.ansible_dir}/box-playbook.yaml \
      -i ${local.ansible_inventory} \
      -e org=${var.org} \
      -e app=${var.app} \
      -e env=${var.env} \
      -e proj_path=${var.proj_path} \
      -e vm_name=${google_compute_instance.satellite.name} \
      -e os_user=${var.os_user} \
      -e ssh_public_key_file=${pathexpand(var.ssh_public_key_file)} \
      "$@" 2>&1 | tee -a ${local.ansible_log}
    exit "$${PIPESTATUS[0]}"
  EOT
}
