// Generated by vibe

export declare const TOPIC_ADMIN_ROLES: readonly ["biz_owner", "admin"];

export declare function archivedRow(card: any): {
    msg_id: string;
    task_id: string;
    channel: string;
    from: string;
    from_box: string;
    ts: string;
    body: string;
    replies: number;
};

export declare function isLatestMessage(msg: any, lastMsgId: string): boolean;

export declare function isTopicCard(msg: any): boolean;

export declare function mayArchiveTopic(msg: any, viewerId: string, me: any): boolean;

export declare function mayChangeTopic(msg: any, viewerId: string, me: any): boolean;

export declare function openingCardId(messages: any[], fallbackId?: string): string;

export declare function topicErrorKey(e: any, scope?: string): string;

export declare function topicFrameDrops(frame: any): string[];

export declare function topicFrameTasks(frame: any, lobbyTaskId?: string): string[];

export declare function withoutCards(rows: any[], msgIds: any[]): any[];

export declare function archiveStamp(data: any): string;

export declare function isRowTopic(size: any, taskId: string, msgId: string, lobbyTaskId?: string): boolean;

export declare function rowCardCandidates(taskId: string, first: any, lobbyTaskId?: string): string[];

export declare function rowTopicState(size: any, msgId: string): {
    state: string;
    msgId: string;
    canArchive: boolean;
    canDelete: boolean;
    replies: number;
};

export declare function topicFrameRows(frame: any, lobbyTaskId?: string): string[];

export declare function withoutTopics(rows: any[], taskIds: any[]): any[];